import type { AppDefinition } from "../adapters/PlatformAdapter.ts";
import type { NamingContext } from "./NamingService.ts";

export interface LocalComposeOptions {
  project: string;
  env: string;
  naming: NamingContext;
  apps: AppDefinition[];
  envVars: Record<string, string>;
}

export interface RemoteComposeOptions {
  project: string;
  env: string;
  naming: NamingContext;
  domain?: string;
  domains?: Record<string, string>;
  apps: AppDefinition[];
  envVars: Record<string, string>;
}

/**
 * Generates docker-compose.yml content for local, remote, and shared Traefik.
 *
 * Pure logic — no I/O, no DI. Takes context, returns YAML string.
 */
export class DockerComposeGenerator {
  /**
   * Generate the shared Traefik compose.
   *
   * This is a static singleton — one per VPS at /opt/alepha/traefik/.
   * It creates the alepha-proxy network that project composes connect to.
   */
  generateTraefik(): string {
    return [
      "# Auto-generated by Alepha. Do not edit.",
      "services:",
      "  traefik:",
      "    image: traefik:v3",
      "    container_name: alepha-traefik",
      "    command:",
      "      - --providers.docker=true",
      "      - --providers.docker.exposedbydefault=false",
      "      - --entrypoints.web.address=:80",
      "      - --entrypoints.websecure.address=:443",
      "      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web",
      "      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json",
      "    ports:",
      '      - "80:80"',
      '      - "443:443"',
      "    volumes:",
      "      - /var/run/docker.sock:/var/run/docker.sock",
      "      - traefik_certs:/letsencrypt",
      "    networks:",
      "      - alepha-proxy",
      "    restart: unless-stopped",
      "",
      "networks:",
      "  alepha-proxy:",
      "    name: alepha-proxy",
      "",
      "volumes:",
      "  traefik_certs:",
      "",
    ].join("\n");
  }

  /**
   * Generate compose for local dev (services only: postgres, redis).
   * Returns null if no services are needed.
   */
  generateLocal(options: LocalComposeOptions): string | null {
    const services: string[] = [];
    const volumes: string[] = [];

    const needsPostgres =
      this.anyAppHas(options.apps, "hasDatabase") &&
      !options.envVars.DATABASE_URL;

    const needsRedis =
      (this.anyAppHas(options.apps, "hasKV") ||
        this.anyAppHas(options.apps, "hasQueue")) &&
      !options.envVars.REDIS_URL;

    const needsRustFS =
      this.anyAppHas(options.apps, "hasBucket") && !options.envVars.S3_ENDPOINT;

    if (needsPostgres) {
      const dbName = `${options.project}_${options.env}`.replace(/-/g, "_");
      services.push(
        [
          "  postgres:",
          "    image: postgres:17-alpine",
          '    ports: ["5432:5432"]',
          "    environment:",
          `      POSTGRES_DB: ${dbName}`,
          "      POSTGRES_USER: alepha",
          "      POSTGRES_PASSWORD: alepha",
          "    volumes:",
          "      - postgres_data:/var/lib/postgresql/data",
        ].join("\n"),
      );
      volumes.push("  postgres_data:");
    }

    if (needsRedis) {
      services.push(
        [
          "  redis:",
          "    image: redis:7-alpine",
          '    ports: ["6379:6379"]',
        ].join("\n"),
      );
    }

    if (needsRustFS) {
      services.push(
        [
          "  rustfs:",
          "    image: rustfs/rustfs:latest",
          '    ports: ["9000:9000"]',
          "    environment:",
          "      RUSTFS_ROOT_USER: alepha",
          "      RUSTFS_ROOT_PASSWORD: alepha",
          "    volumes:",
          "      - rustfs_data:/data",
        ].join("\n"),
      );
      volumes.push("  rustfs_data:");
    }

    if (services.length === 0) {
      return null;
    }

    const parts = [
      "# Auto-generated by Alepha. Do not edit.",
      "services:",
      ...services,
    ];

    if (volumes.length > 0) {
      parts.push("", "volumes:", ...volumes);
    }

    return `${parts.join("\n")}\n`;
  }

  /**
   * Generate compose for a remote project.
   *
   * - With `domain`: app connects to shared alepha-proxy network + Traefik labels
   * - Without `domain`: app exposed directly on port 3000, no Traefik involvement
   *
   * Traefik itself is NEVER in this compose — it's a separate shared compose.
   */
  generateRemote(options: RemoteComposeOptions): string {
    const hasDomain =
      !!options.domain || Object.keys(options.domains ?? {}).length > 0;
    const services: string[] = [];
    const volumes: string[] = [];

    // App containers
    const isMultiApp = options.apps.length > 1;
    const needsInternal =
      hasDomain && this.anyAppNeedsInternal(options.apps, options.envVars);

    for (let i = 0; i < options.apps.length; i++) {
      const app = options.apps[i];
      const serviceName = isMultiApp ? `app-${app.name}` : "app";
      const buildPath = isMultiApp ? `./dist/${app.name}` : "./dist";

      const appLines = [
        `  ${serviceName}:`,
        `    build: ${buildPath}`,
        `    env_file: .env.${options.env}`,
      ];

      const appDomain = this.resolveAppDomain(
        app.name,
        isMultiApp,
        options.domain,
        options.domains,
      );

      if (appDomain) {
        // Traefik mode: labels for routing + SSL, connect to shared network
        const routerName = serviceName.replace(/-/g, "");
        appLines.push(
          "    labels:",
          "      - traefik.enable=true",
          `      - traefik.http.routers.${routerName}.rule=Host(\`${appDomain}\`)`,
          `      - traefik.http.routers.${routerName}.tls.certresolver=letsencrypt`,
          "    networks:",
          "      - alepha-proxy",
        );
        if (needsInternal) {
          appLines.push("      - internal");
        }
      } else {
        // Direct mode: expose port, no Traefik
        const port = 3000 + i;
        appLines.push("    ports:", `      - "${port}:3000"`);
      }

      appLines.push("    restart: unless-stopped");

      // Dependencies
      const deps: string[] = [];
      if (app.resources.hasDatabase && !options.envVars.DATABASE_URL) {
        deps.push("      - postgres");
      }
      if (
        (app.resources.hasKV || app.resources.hasQueue) &&
        !options.envVars.REDIS_URL
      ) {
        deps.push("      - redis");
      }
      if (app.resources.hasBucket && !options.envVars.S3_ENDPOINT) {
        deps.push("      - rustfs");
      }
      if (deps.length > 0) {
        appLines.push("    depends_on:", ...deps);
      }

      services.push(appLines.join("\n"));
    }

    // Postgres
    const needsPostgres =
      this.anyAppHas(options.apps, "hasDatabase") &&
      !options.envVars.DATABASE_URL;

    if (needsPostgres) {
      const dbName = `${options.project}_${options.env}`.replace(/-/g, "_");
      const pgLines = [
        "  postgres:",
        "    image: postgres:17-alpine",
        "    environment:",
        `      POSTGRES_DB: ${dbName}`,
        "      POSTGRES_USER: alepha",
        "      POSTGRES_PASSWORD: ${DB_PASSWORD}",
        "    volumes:",
        "      - postgres_data:/var/lib/postgresql/data",
      ];
      if (hasDomain) {
        pgLines.push("    networks:", "      - internal");
      }
      pgLines.push("    restart: unless-stopped");
      services.push(pgLines.join("\n"));
      volumes.push("  postgres_data:");
    }

    // Redis
    const needsRedis =
      (this.anyAppHas(options.apps, "hasKV") ||
        this.anyAppHas(options.apps, "hasQueue")) &&
      !options.envVars.REDIS_URL;

    if (needsRedis) {
      const redisLines = ["  redis:", "    image: redis:7-alpine"];
      if (hasDomain) {
        redisLines.push("    networks:", "      - internal");
      }
      redisLines.push("    restart: unless-stopped");
      services.push(redisLines.join("\n"));
    }

    // RustFS (S3-compatible object storage)
    const needsRustFS =
      this.anyAppHas(options.apps, "hasBucket") && !options.envVars.S3_ENDPOINT;

    if (needsRustFS) {
      const rustfsLines = [
        "  rustfs:",
        "    image: rustfs/rustfs:latest",
        "    environment:",
        "      RUSTFS_ROOT_USER: alepha",
        "      RUSTFS_ROOT_PASSWORD: ${S3_SECRET_KEY}",
        "    volumes:",
        "      - rustfs_data:/data",
      ];
      if (hasDomain) {
        rustfsLines.push("    networks:", "      - internal");
      }
      rustfsLines.push("    restart: unless-stopped");
      services.push(rustfsLines.join("\n"));
      volumes.push("  rustfs_data:");
    }

    const parts = [
      "# Auto-generated by Alepha. Do not edit.",
      "services:",
      ...services,
    ];

    // Networks — only when domain is set (connect to shared Traefik network)
    if (hasDomain) {
      parts.push("", "networks:", "  alepha-proxy:", "    external: true");
      if (needsInternal) {
        parts.push("  internal:");
      }
    }

    if (volumes.length > 0) {
      parts.push("", "volumes:", ...volumes);
    }

    return `${parts.join("\n")}\n`;
  }

  /**
   * Resolve the domain for an app.
   *
   * Priority:
   * 1. `domains[appName]` — explicit override (e.g. shop → myshop.com)
   * 2. `<appName>.<domain>` — convention for multi-app (e.g. api → api.company.com)
   * 3. `domain` — used directly for single-app projects (e.g. myapp.com)
   */
  resolveAppDomain(
    appName: string,
    isMultiApp: boolean,
    domain?: string,
    domains?: Record<string, string>,
  ): string | undefined {
    if (domains?.[appName]) {
      return domains[appName];
    }
    if (domain && isMultiApp) {
      return `${appName}.${domain}`;
    }
    return domain;
  }

  protected anyAppHas(
    apps: AppDefinition[],
    resource: keyof AppDefinition["resources"],
  ): boolean {
    return apps.some((app) => app.resources[resource]);
  }

  protected anyAppNeedsInternal(
    apps: AppDefinition[],
    envVars: Record<string, string>,
  ): boolean {
    return (
      (this.anyAppHas(apps, "hasDatabase") && !envVars.DATABASE_URL) ||
      ((this.anyAppHas(apps, "hasKV") || this.anyAppHas(apps, "hasQueue")) &&
        !envVars.REDIS_URL) ||
      (this.anyAppHas(apps, "hasBucket") && !envVars.S3_ENDPOINT)
    );
  }
}
