import { Alepha } from "alepha";
import { describe, it } from "vitest";

import type { CapacitorOptions } from "../atoms/capacitorOptions.ts";
import { CapacitorProject } from "../services/CapacitorProject.ts";

const options: CapacitorOptions = {
  appId: "dev.alepha.mobile",
  appName: "Mobile",
  scheme: "mobile",
};

describe("CapacitorProject", () => {
  const project = (env: Record<string, string> = {}) =>
    Alepha.create({ env }).inject(CapacitorProject);

  describe("resolveApiUrl", () => {
    it("takes the declared apiUrl over PUBLIC_URL", ({ expect }) => {
      expect(
        project({ PUBLIC_URL: "https://public.test" }).resolveApiUrl({
          ...options,
          apiUrl: "https://api.test",
        }),
      ).toBe("https://api.test");
    });

    it("falls back to PUBLIC_URL", ({ expect }) => {
      expect(
        project({ PUBLIC_URL: "https://public.test" }).resolveApiUrl(options),
      ).toBe("https://public.test");
    });

    it("answers undefined when neither is set", ({ expect }) => {
      expect(project().resolveApiUrl(options)).toBeUndefined();
    });

    it("refuses a path rather than trimming it", ({ expect }) => {
      expect(() =>
        project().resolveApiUrl({ ...options, apiUrl: "https://api.test/v1" }),
      ).toThrow(/must be an origin/);
    });

    it("refuses what is not an http origin", ({ expect }) => {
      expect(() =>
        project().resolveApiUrl({ ...options, apiUrl: "api.test" }),
      ).toThrow(/not an absolute URL/);
      expect(() =>
        project().resolveApiUrl({ ...options, apiUrl: "ftp://api.test" }),
      ).toThrow(/http or https/);
    });
  });

  describe("renderCapacitorConfig", () => {
    it("writes the identity and the shell's directory", ({ expect }) => {
      expect(project().renderCapacitorConfig(options)).toBe(
        [
          "// Generated by `alepha capacitor` from alepha.config.ts.",
          "// Change capacitor({ ... }) there: the next command rewrites this file.",
          'import type { CapacitorConfig } from "@capacitor/cli";',
          "",
          "const config: CapacitorConfig = {",
          '  appId: "dev.alepha.mobile",',
          '  appName: "Mobile",',
          '  webDir: "dist-capacitor/public",',
          "};",
          "",
          "export default config;",
          "",
        ].join("\n"),
      );
    });

    it("merges the extra config", ({ expect }) => {
      const content = project().renderCapacitorConfig({
        ...options,
        config: { plugins: { SplashScreen: { launchShowDuration: 8000 } } },
      });

      expect(content).toContain(
        "  plugins: {\n    SplashScreen: {\n      launchShowDuration: 8000,\n    },\n  },",
      );
    });

    it("refuses server.url and the plugin's own keys", ({ expect }) => {
      expect(() =>
        project().renderCapacitorConfig({
          ...options,
          config: { server: { url: "http://192.168.1.2:5173" } },
        }),
      ).toThrow(/server\.url/);
      expect(() =>
        project().renderCapacitorConfig({
          ...options,
          config: { appId: "other.id" },
        }),
      ).toThrow(/cannot set appId/);
    });
  });
});
