import { Alepha } from "alepha";
import { describe, it } from "vitest";

import type { CapacitorOptions } from "../atoms/capacitorOptions.ts";
import { CapacitorProject } from "../services/CapacitorProject.ts";

const options: CapacitorOptions = {
  appId: "dev.alepha.mobile",
  appName: "Mobile",
  scheme: "mobile",
};

describe("CapacitorProject", () => {
  const project = (env: Record<string, string> = {}) =>
    Alepha.create({ env }).inject(CapacitorProject);

  describe("resolveApiUrl", () => {
    it("takes the declared apiUrl over PUBLIC_URL", ({ expect }) => {
      expect(
        project({ PUBLIC_URL: "https://public.test" }).resolveApiUrl({
          ...options,
          apiUrl: "https://api.test",
        }),
      ).toBe("https://api.test");
    });

    it("falls back to PUBLIC_URL", ({ expect }) => {
      expect(
        project({ PUBLIC_URL: "https://public.test" }).resolveApiUrl(options),
      ).toBe("https://public.test");
    });

    it("answers undefined when neither is set", ({ expect }) => {
      expect(project().resolveApiUrl(options)).toBeUndefined();
    });

    it("refuses a path rather than trimming it", ({ expect }) => {
      expect(() =>
        project().resolveApiUrl({ ...options, apiUrl: "https://api.test/v1" }),
      ).toThrow(/must be an origin/);
    });

    it("refuses what is not an http origin", ({ expect }) => {
      expect(() =>
        project().resolveApiUrl({ ...options, apiUrl: "api.test" }),
      ).toThrow(/not an absolute URL/);
      expect(() =>
        project().resolveApiUrl({ ...options, apiUrl: "ftp://api.test" }),
      ).toThrow(/http or https/);
    });
  });

  describe("renderCapacitorConfig", () => {
    it("writes the identity and the shell's directory", ({ expect }) => {
      expect(project().renderCapacitorConfig(options)).toBe(
        [
          "// Generated by `alepha capacitor` from alepha.config.ts.",
          "// Change capacitor({ ... }) there: the next command rewrites this file.",
          'import type { CapacitorConfig } from "@capacitor/cli";',
          "",
          "const config: CapacitorConfig = {",
          '  appId: "dev.alepha.mobile",',
          '  appName: "Mobile",',
          '  webDir: "dist-capacitor/public",',
          "  plugins: {",
          "    SplashScreen: {",
          "      launchAutoHide: true,",
          "      launchShowDuration: 8000,",
          "    },",
          "  },",
          "};",
          "",
          "export default config;",
          "",
        ].join("\n"),
      );
    });

    it("merges the extra config over the splash backstop", ({ expect }) => {
      const content = project().renderCapacitorConfig({
        ...options,
        config: {
          plugins: {
            SplashScreen: { launchShowDuration: 12000 },
            App: { disableBackButtonHandler: false },
          },
        },
      });

      expect(content).toContain(
        "    SplashScreen: {\n      launchAutoHide: true,\n      launchShowDuration: 12000,\n    },",
      );
      expect(content).toContain(
        "    App: {\n      disableBackButtonHandler: false,",
      );
    });

    it("refuses server.url and the plugin's own keys", ({ expect }) => {
      expect(() =>
        project().renderCapacitorConfig({
          ...options,
          config: { server: { url: "http://192.168.1.2:5173" } },
        }),
      ).toThrow(/server\.url/);
      expect(() =>
        project().renderCapacitorConfig({
          ...options,
          config: { appId: "other.id" },
        }),
      ).toThrow(/cannot set appId/);
    });
  });

  describe("the live updater", () => {
    const pem =
      "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAtest\n-----END RSA PUBLIC KEY-----\n";

    it("silences an installed updater the app does not use", ({ expect }) => {
      const content = project().renderCapacitorConfig(options, {
        installed: true,
      });
      expect(content).toContain("CapacitorUpdater: {");
      expect(content).toContain("autoUpdate: false,");
      // No vendor default: every URL blanked, stats off.
      expect(content).toContain('updateUrl: "",');
      expect(content).toContain('statsUrl: "",');
      expect(content).toContain('channelUrl: "",');
      expect(content).not.toContain("publicKey");
    });

    it("writes the self-hosted policy with the publisher's public key", ({
      expect,
    }) => {
      const content = project().renderCapacitorConfig(
        {
          ...options,
          config: { plugins: { CapacitorUpdater: { autoUpdate: true } } },
        },
        { installed: true, publicKey: pem },
      );
      expect(content).toContain("autoUpdate: false,");
      expect(content).toContain("allowModifyUrl: true,");
      expect(content).toContain("allowManualBundleError: true,");
      expect(content).toContain(`publicKey: ${JSON.stringify(pem)},`);
    });

    it("leaves a project without the updater alone", ({ expect }) => {
      expect(project().renderCapacitorConfig(options)).not.toContain(
        "CapacitorUpdater",
      );
    });

    it("tells the shell where the OTA server is", ({ expect }) => {
      const ota = { ...options, ota: { publicKey: pem } };
      expect(
        project().publicConfig(ota, "bundled", "https://api.test").ota,
      ).toEqual({ url: "https://api.test" });
      expect(
        project().publicConfig(
          { ...ota, ota: { publicKey: pem, url: "https://ota.test/x" } },
          "bundled",
          "https://api.test",
        ).ota,
      ).toEqual({ url: "https://ota.test" });
      expect(() => project().publicConfig(ota, "bundled", undefined)).toThrow(
        /ota\.url, or apiUrl/,
      );
      expect(
        project().publicConfig(options, "bundled", "https://api.test").ota,
      ).toBeUndefined();
    });
  });
});
