name: Setup
description: Setup Node.js with Yarn

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Prepare Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: "24.x"
        cache: "yarn"

    - name: Install Dependencies
      run: yarn
      shell: bash
