ignores:
    - 'alepha'
    - '@alepha/ui'
    - '@alepha/mantine'
    - '@alepha/mqtt'
    - '@alepha/devtools'
    - '@vitejs/plugin-react'
    - 'jsdom'
    - '@vitest/coverage-v8'
    - 'drizzle-kit'
    - 'swagger-ui-dist'
    - 'vite'
    - '@types/react'
    - 'animate.css'
    - 'marked-highlight'
    - 'highlight.js'
    - '@biomejs/biome'
    - 'typescript'
    - 'vitest'
    - 'react-is'
    - '@playwright/test'
    - 'wrangler'
    - 'vercel'
    - '@fontsource/jetbrains-mono'
    - '@types/bun'
    - 'better-sqlite3'
    - 'surge'
    - 'bun'
    - 'bun:sqlite'
    - 'bun:test'
    - 'cloudflare:workers'
    - 'tailwindcss'
    - '@tailwindcss/vite'
    - '@types/react-dom'
    - '@types/react-is'
    - '@fontsource-variable/inter'
    - '@fontsource-variable/jetbrains-mono'
    - 'date-fns'
    - 'tw-animate-css'
    - 'shadcn'

ignore-patterns:
    - 'dist'
    - 'assets'
