ignores:
    - 'alepha'
    - '@vitejs/plugin-react'
    - 'jsdom'
    - '@alepha/ui'
    - '@alepha/react'
    - '@vitest/coverage-v8'
    - 'drizzle-kit'
    - 'swagger-ui-dist'
    - 'vite'
    - '@types/react'
    - 'animate.css'
    - 'marked-highlight'
    - 'highlight.js'
    - '@biomejs/biome'
    - 'typescript'
    - 'vitest'
    - 'wrangler'
    - 'vercel'
    - '@fontsource/jetbrains-mono'
ignore-patterns:
    - 'dist'
    - 'assets'
