services:

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  s3mock:
    restart: always
    image: adobe/s3mock:latest
    ports:
      - "9090:9090"

  verdaccio:
    restart: always
    image: verdaccio/verdaccio:latest
    ports:
      - "4873:4873"
    volumes:
      - verdaccio-storage:/verdaccio/storage
      - verdaccio-conf:/verdaccio/conf

volumes:
  verdaccio-storage:
  verdaccio-conf:
