{
 "title": "Node.js Server Metrics",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nodejs_cpu_usage_percent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nodejs_memory_usage_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nodejs_heap_usage_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "GC Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum[1m]) / rate(nodejs_gc_duration_seconds_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}