import { defineConfig } from "alepha/cli/config";
import { devtools } from "alepha/cli/devtools";
import { platform } from "alepha/cli/platform";

export default defineConfig({
  // Dev ports live in the 33xx band, which `playwright.port.ts` keeps strictly
  // DISJOINT from the 4300-4999 e2e band. 3302 docs, 3303 lore, 3304
  // playground, 3305 shop, 3306 errors, 3311 ssr, so this one takes 3307.
  dev: { port: 3307 },
  plugins: [
    /*
     * Dev-server only: the plugin is registered by the CLI, never by the app, so
     * nothing here reaches the deployed Worker.
     */
    devtools(),
    platform({
      /*
       * Worker secrets are auto-detected from the build manifest's `env` list
       * (every `$env`-declared key) and resolved from `process.env` at deploy
       * time, so there is no `secrets.keys` to maintain. This app needs exactly
       * one that has no safe default: `APP_SECRET`, which Alepha refuses to boot
       * without in production, and which is also what encrypts every TOTP
       * secret at rest. It lives in `.env.production`, which is gitignored.
       *
       * ⚠️ Rotating `APP_SECRET` makes every stored TOTP secret undecryptable,
       * which locks out every enrolled user at once. There is no migration for
       * that short of clearing the enrollments.
       *
       * The D1 binding is generated by the build, which is why the migrations
       * under `migrations/sqlite/` are already the right dialect.
       */
      environments: {
        production: {
          domain: "totp-example.alepha.dev",
          adapter: "cloudflare",
        },
      },
    }),
  ],
});
