import { Badge, Button, useToast, cn } from "@alepha/ui";
import {
  DataTable,
  type DataTableFilterFields,
  type DataTableFilterValues,
} from "@alepha/ui/table";
import { z } from "alepha";
import type { Page } from "alepha";
import { useClient } from "alepha/react";
import {
  AtSign,
  Bot,
  CircleDot,
  Shield,
  Tag,
  Trash2,
  UserPlus,
  Users,
} from "lucide-react";
import { useCallback } from "react";

import type { ShowcaseMember } from "@/showcase/ShowcaseMembers.ts";
import { Showcase } from "@/web/components/Showcase.tsx";

/**
 * The one page that exercises the data path end to end: `useClient` resolves
 * `LinkProvider`, which reads the action registry and dispatches
 * `findShowcaseMembers` - in process during SSR, over HTTP in the browser.
 */
const KNOBS = z.object({
  // `50` is here so "Full height" has something to prove: at 20 rows the body
  // only overflows on a short viewport, and a scroller nobody can see is
  // indistinguishable from one that does not work.
  pageSize: z
    .enum(["5", "10", "20", "50"])
    .default("10")
    .meta({ title: "Page size" }),
  selectable: z.boolean().default(true).meta({ title: "Row selection" }),
  filters: z.boolean().default(true).meta({ title: "Filter toolbar" }),
  // Both empty states, reachable from the panel. "No match" is not faked: it
  // seeds the search box with a term the fixture cannot match, so the state
  // is produced by the same filter detection a reader's own typing would go
  // through.
  //
  // "Custom" is that same no-filter state dressed by the caller, which is what
  // a real page does with `emptyState`: the table is empty because the reader
  // has not created anything yet, and the answer to that is a button, not an
  // apology. Worth a slot of its own because the stock wording is the least
  // interesting thing a table can say when it is empty.
  emptyState: z
    .enum(["Off", "No items", "No match", "Custom"])
    .default("Off")
    .meta({ title: "Empty state" }),
  // The layout an application actually mounts this in: the table takes the
  // pane's height and its BODY scrolls, so the filter bar and the pagination
  // footer stay put and the sticky header stays against the top of the rows.
  // ON by default, because that is the arrangement every real page uses and
  // the showcase should open on the real one. The switch is kept so the
  // content-height variant can still be seen.
  fullHeight: z.boolean().default(true).meta({ title: "Full height" }),
});

/**
 * The bar's filters, one of each shape a bar has to survive: the search box, a
 * single select with is / is not, a plain single select, a multi select on a
 * column holding one value (any / none of), a multi select on a column
 * holding several (any / all / none of), and a text-contains on one column.
 *
 * Each filter carries its own schema, and the table builds the form from
 * them. An operator is a key of its own (`statusOp`, `rolesOp`, `tagsOp`),
 * generated by the table from `operators` rather than declared here: being a
 * key is what lets it persist and travel in a share link like any other
 * filter, and a filter left on its default operator carries no key at all.
 *
 * ⚠️ Every option LABEL is capitalized; no stored value is. `status` holds
 * `active` in the dataset and in the query, and only the label reads "Active".
 * Capitalizing the value instead would leave the filter matching no row.
 */
const FILTER_FIELDS = {
  search: { preset: "search" },
  status: {
    schema: z.enum(["active", "invited", "disabled"]),
    label: "Status",
    icon: CircleDot,
    placeholder: "Any status",
    operators: "is",
    optionLabel: (status: string) =>
      status.charAt(0).toUpperCase() + status.slice(1),
  },
  team: {
    schema: z.enum(["Platform", "Design", "Growth", "Security"]),
    label: "Team",
    icon: Users,
    placeholder: "Any team",
  },
  // Multi choice. An array schema is what makes `Control` render a
  // multi-select, so the shape of the field IS the choice of control.
  roles: {
    schema: z.array(z.enum(["Owner", "Admin", "Member", "Viewer"])),
    label: "Roles",
    icon: Shield,
    placeholder: "Any role",
    operators: "any-none",
  },
  tags: {
    schema: z.array(
      z.enum(["remote", "on-call", "mentor", "contractor", "beta"]),
    ),
    label: "Tags",
    icon: Tag,
    placeholder: "Any tag",
    operators: "any-all-none",
    items: [
      { value: "remote", label: "Remote" },
      { value: "on-call", label: "On-call" },
      { value: "mentor", label: "Mentor" },
      { value: "contractor", label: "Contractor" },
      { value: "beta", label: "Beta" },
    ],
  },
  // Text contains, on a single column - distinct from `search`, which spans
  // name and email at once.
  email: {
    schema: z.string(),
    label: "Email",
    icon: AtSign,
    placeholder: "Email contains…",
  },
} satisfies DataTableFilterFields;

/**
 * "No items" is the one state the fixture cannot reach on its own: it always
 * has 75 rows, and everything that narrows them to zero is a filter, which is
 * the OTHER state. So this answers with an empty page instead of asking the
 * server.
 */
const fetchNothing = async (): Promise<Page<ShowcaseMember>> => ({
  content: [],
  page: {
    number: 0,
    size: 10,
    offset: 0,
    numberOfElements: 0,
    totalElements: 0,
    totalPages: 1,
    isEmpty: true,
    isFirst: true,
    isLast: true,
  },
});

const STATUS_TONE: Record<string, "success" | "warning" | "danger"> = {
  active: "success",
  invited: "warning",
  disabled: "danger",
};

const Table = () => {
  const toast = useToast();
  const client = useClient() as unknown as {
    findShowcaseMembers: (a: {
      query: Record<string, unknown>;
    }) => Promise<Page<ShowcaseMember>>;
  };

  const fetcher = useCallback(
    async (params: {
      page: number;
      size: number;
      sort?: string;
      filters?: DataTableFilterValues<typeof FILTER_FIELDS>;
    }) =>
      client.findShowcaseMembers({
        query: {
          page: params.page,
          size: params.size,
          sort: params.sort,
          // Never pass undefined into a filter: an empty box omits the key.
          search: params.filters?.search || undefined,
          status: params.filters?.status || undefined,
          team: params.filters?.team || undefined,
          // ⚠️ Joined, not sent as an array. A repeated query key is the one
          // shape that differs between the in-process SSR dispatch and the
          // HTTP one, so a comma-joined string keeps both paths identical.
          roles: params.filters?.roles?.length
            ? params.filters.roles.join(",")
            : undefined,
          tags: params.filters?.tags?.length
            ? params.filters.tags.join(",")
            : undefined,
          // Forwarded as they come: the table already drops a key that is
          // undefined, and the server reads an operator only beside its value.
          statusOp: params.filters?.statusOp,
          rolesOp: params.filters?.rolesOp,
          tagsOp: params.filters?.tagsOp,
          email: params.filters?.email || undefined,
        },
      }),
    [client],
  );

  return (
    <Showcase
      id="blocks/Table"
      title="Table"
      description="Server-paged, filtered and sortable."
      fill
      schema={KNOBS}
      initialValues={{
        pageSize: "10",
        selectable: true,
        filters: true,
        emptyState: "Off",
        fullHeight: true,
      }}
    >
      {(v) => (
        <DataTable<ShowcaseMember, typeof FILTER_FIELDS>
          // `defaultSize`, `defaultHidden`, `persistenceKey` and `seedValues`
          // are read at mount, so every knob that feeds one has to be in this
          // key or the switch moves and the table does not. `fullHeight` is
          // deliberately absent: it feeds a class, and remounting on it would
          // throw the fetch away to change a style.
          key={`${v.pageSize}-${v.selectable}-${v.filters}-${v.emptyState}`}
          className={cn("min-h-0", v.fullHeight && "flex-1")}
          // Dropped while an empty state is forced. Persistence would
          // otherwise decide which of the two states appears: a search left in
          // the box from an earlier visit is still an active filter, so "No
          // items" would quietly render "No match".
          persistenceKey={v.emptyState === "Off" ? "ui.members" : undefined}
          fetch={
            v.emptyState === "No items" || v.emptyState === "Custom"
              ? fetchNothing
              : fetcher
          }
          // Only the custom slot is filled here. The other three modes are
          // showing what the table says on its own, which is the point of
          // having them next to this one.
          emptyState={
            v.emptyState === "Custom"
              ? {
                  icon: UserPlus,
                  title: "No members yet",
                  description:
                    "Invite someone and they will show up here, with their team and role.",
                  action: (
                    <Button
                      size="sm"
                      onClick={() => toast.success("Invitation sent")}
                    >
                      <UserPlus />
                      Invite a member
                    </Button>
                  ),
                }
              : undefined
          }
          defaultSize={Number(v.pageSize)}
          filters={
            // "No match" implies the filter bar, whatever the toolbar knob
            // says: the state only exists when something is filtering, so the
            // combination the knob would otherwise allow has no meaning.
            v.filters || v.emptyState === "No match"
              ? {
                  fields: FILTER_FIELDS,
                  // Linkable, which is what puts the toolbar's filter MENU
                  // (Share + Reset) in place of the bare reset icon button.
                  // The showcase is the only place both shapes can be
                  // compared, so it demonstrates the one that has more in it.
                  fromQuery: true,
                  seedValues:
                    v.emptyState === "No match"
                      ? { search: "nobody" }
                      : undefined,
                }
              : undefined
          }
          // A row action may be a group, one level deep, rendered as a
          // submenu. The showcase carries one because a submenu is the one
          // shape a jsdom spec cannot prove lays out.
          rowActions={(m) => [
            {
              label: "Agent Prompts",
              icon: Bot,
              children: [
                {
                  label: "Copy invite prompt",
                  onClick: () => toast.success(`Prompt copied for ${m.name}`),
                },
                {
                  label: "Copy review prompt",
                  onClick: () => toast.success(`Review copied for ${m.name}`),
                },
              ],
            },
            {
              label: "Remove member",
              icon: Trash2,
              destructive: true,
              onClick: () => toast.success(`${m.name} removed`),
            },
          ]}
          bulkActions={
            v.selectable
              ? [
                  {
                    label: "Export selected",
                    onClick: (items, ctx) => {
                      ctx.clearSelection();
                      return Promise.resolve(void items);
                    },
                  },
                ]
              : undefined
          }
          columns={{
            // `sortable` is opt-in per COLUMN, and without it the header is
            // inert however well the server sorts. `ShowcaseMembers` has
            // honoured `sort` from the beginning and the fetcher has always
            // forwarded it, so the whole path worked except for the one flag
            // that lets a reader reach it - and this page's own description
            // says "sortable".
            name: {
              label: "Name",
              sortable: true,
              cell: (m) => <span className="font-medium">{m.name}</span>,
            },
            email: {
              label: "Email",
              sortable: true,
              cell: (m) => (
                <span className="text-muted-foreground truncate">
                  {m.email}
                </span>
              ),
            },
            // Both columns start visible. Hiding one is what the "Toggle
            // columns" menu is for, and a knob doing the same thing from the
            // side panel only made the menu look decorative. (`defaultHidden`
            // is per COLUMN, if a page wants one hidden from the start: the
            // table has no defaultHiddenColumns prop, that one belongs to
            // AdminUsers.)
            team: {
              label: "Team",
              sortable: true,
              cell: (m) => m.team,
            },
            role: {
              label: "Role",
              cell: (m) => <Badge variant="outline">{m.role}</Badge>,
            },
            tags: {
              label: "Tags",
              cell: (m) => (
                <div className="flex flex-wrap gap-1">
                  {m.tags.map((tag) => (
                    <Badge key={tag} variant="secondary">
                      {tag}
                    </Badge>
                  ))}
                </div>
              ),
            },
            status: {
              label: "Status",
              // `tone` is only meaningful with variant="tint": every other
              // variant paints its own background and leaves the label
              // unreadable over a pale tint.
              cell: (m) => (
                <Badge variant="tint" tone={STATUS_TONE[m.status]}>
                  {/* Capitalized for display only; the row still holds the
                      lowercase value the filter matches on. */}
                  {m.status.charAt(0).toUpperCase() + m.status.slice(1)}
                </Badge>
              ),
            },
          }}
        />
      )}
    </Showcase>
  );
};

export default Table;
