import {
  $env,
  $hook,
  $inject,
  Alepha,
  AlephaError,
  type FileLike,
  t,
} from "alepha";
import { $logger } from "alepha/logger";
import { FileNotFoundError } from "../errors/FileNotFoundError.ts";
import { $bucket } from "../primitives/$bucket.ts";
import type { FileStorageProvider } from "./FileStorageProvider.ts";

// ---------------------------------------------------------------------------------------------------------------------

/**
 * R2Bucket interface matching Cloudflare's R2 API.
 */
export interface R2Bucket {
  put(
    key: string,
    value:
      | ReadableStream
      | ArrayBuffer
      | ArrayBufferView
      | string
      | Blob
      | null,
    options?: R2PutOptions,
  ): Promise<R2Object | null>;
  get(key: string, options?: R2GetOptions): Promise<R2ObjectBody | null>;
  head(key: string): Promise<R2Object | null>;
  delete(keys: string | string[]): Promise<void>;
  list(options?: R2ListOptions): Promise<R2Objects>;
  createMultipartUpload(
    key: string,
    options?: R2MultipartOptions,
  ): Promise<R2MultipartUpload>;
}

export interface R2Object {
  key: string;
  version: string;
  size: number;
  etag: string;
  httpEtag: string;
  checksums: R2Checksums;
  uploaded: Date;
  httpMetadata?: R2HTTPMetadata;
  customMetadata?: Record<string, string>;
  range?: R2Range;
  storageClass: string;
}

export interface R2ObjectBody extends R2Object {
  body: ReadableStream;
  bodyUsed: boolean;
  arrayBuffer(): Promise<ArrayBuffer>;
  text(): Promise<string>;
  json<T>(): Promise<T>;
  blob(): Promise<Blob>;
}

export interface R2PutOptions {
  onlyIf?: R2Conditional;
  httpMetadata?: R2HTTPMetadata;
  customMetadata?: Record<string, string>;
  md5?: ArrayBuffer | string;
  sha1?: ArrayBuffer | string;
  sha256?: ArrayBuffer | string;
  sha384?: ArrayBuffer | string;
  sha512?: ArrayBuffer | string;
  storageClass?: string;
}

export interface R2GetOptions {
  onlyIf?: R2Conditional;
  range?: R2Range;
}

export interface R2ListOptions {
  limit?: number;
  prefix?: string;
  cursor?: string;
  delimiter?: string;
  startAfter?: string;
  include?: ("httpMetadata" | "customMetadata")[];
}

export interface R2Objects {
  objects: R2Object[];
  truncated: boolean;
  cursor?: string;
  delimitedPrefixes: string[];
}

export interface R2Checksums {
  md5?: ArrayBuffer;
  sha1?: ArrayBuffer;
  sha256?: ArrayBuffer;
  sha384?: ArrayBuffer;
  sha512?: ArrayBuffer;
}

export interface R2HTTPMetadata {
  contentType?: string;
  contentLanguage?: string;
  contentDisposition?: string;
  contentEncoding?: string;
  cacheControl?: string;
  cacheExpiry?: Date;
}

export interface R2Conditional {
  etagMatches?: string;
  etagDoesNotMatch?: string;
  uploadedBefore?: Date;
  uploadedAfter?: Date;
  secondsGranularity?: boolean;
}

export interface R2Range {
  offset?: number;
  length?: number;
  suffix?: number;
}

export interface R2MultipartOptions {
  httpMetadata?: R2HTTPMetadata;
  customMetadata?: Record<string, string>;
  storageClass?: string;
}

export interface R2MultipartUpload {
  key: string;
  uploadId: string;
  uploadPart(
    partNumber: number,
    value: ReadableStream | ArrayBuffer | ArrayBufferView | string | Blob,
  ): Promise<R2UploadedPart>;
  abort(): Promise<void>;
  complete(uploadedParts: R2UploadedPart[]): Promise<R2Object>;
}

export interface R2UploadedPart {
  partNumber: number;
  etag: string;
}

// ---------------------------------------------------------------------------------------------------------------------

/**
 * Cloudflare R2 storage provider.
 *
 * Uses a single R2 bucket binding for all $bucket primitives.
 * Files are organized as: {APP_NAME}/{bucketName}/{fileId}
 *
 * **Required environment variables:**
 * - `R2_BUCKET_NAME` - The actual R2 bucket name in Cloudflare
 *
 * **Optional (uses core Alepha env):**
 * - `APP_NAME` - Prefix for all files (for multi-app setups sharing one R2 bucket)
 *
 * @example
 * ```bash
 * # .env
 * APP_NAME=myapp        # optional, used as prefix
 * R2_BUCKET_NAME=storage
 * ```
 *
 * @example
 * ```toml
 * # wrangler.toml - automatically generated by alepha build
 * [[r2_buckets]]
 * binding = "R2"
 * bucket_name = "storage"
 * ```
 *
 * @example
 * ```ts
 * // Define buckets with validation rules
 * const avatars = $bucket({
 *   name: "avatars",
 *   maxFileSize: 5 * 1024 * 1024,
 *   allowedMimeTypes: ["image/*"],
 * });
 *
 * const documents = $bucket({
 *   name: "documents",
 *   maxFileSize: 50 * 1024 * 1024,
 *   allowedMimeTypes: ["application/pdf"],
 * });
 *
 * // Files stored at: myapp/avatars/uuid.png, myapp/documents/uuid.pdf
 * ```
 */
export class CloudflareR2Provider implements FileStorageProvider {
  protected readonly alepha = $inject(Alepha);
  protected readonly log = $logger();
  protected readonly env = $env(
    t.object({
      /**
       * The actual R2 bucket name in Cloudflare.
       */
      R2_BUCKET_NAME: t.string({
        description: "R2 bucket name in Cloudflare",
      }),
    }),
  );

  protected r2?: R2Bucket;

  /**
   * Get the R2 bucket name from environment.
   */
  public get bucketName(): string {
    return this.env.R2_BUCKET_NAME;
  }

  /**
   * Get the optional prefix from APP_NAME environment variable.
   * Used for multi-app setups sharing the same R2 bucket.
   */
  public get prefix(): string | undefined {
    return this.alepha.env.APP_NAME;
  }

  protected readonly onStart = $hook({
    on: "start",
    handler: async () => {
      const cloudflareEnv = this.alepha.get("cloudflare.env") as
        | Record<string, unknown>
        | undefined;
      if (!cloudflareEnv) {
        throw new AlephaError(
          "Cloudflare Workers environment not found in Alepha store under 'cloudflare.env'.",
        );
      }

      const binding = cloudflareEnv[this.bucketName] as R2Bucket | undefined;
      if (!binding) {
        throw new AlephaError(
          `R2 binding '${this.bucketName}' not found in Cloudflare Workers environment.`,
        );
      }

      this.r2 = binding;

      const prefixStr = this.prefix ? `${this.prefix}/` : "";
      this.log.info(
        `R2 storage ready (bucket: ${this.bucketName}, prefix: ${prefixStr || "(none)"})`,
      );

      for (const bucket of this.alepha.primitives($bucket)) {
        if (bucket.provider !== this) {
          continue;
        }
        this.log.debug(
          `Bucket '${bucket.name}' -> ${prefixStr}${bucket.name}/`,
        );
      }
    },
  });

  public async upload(
    bucketName: string,
    file: FileLike,
    fileId?: string,
  ): Promise<string> {
    const r2 = this.getR2();
    fileId ??= this.createId(file.name);
    const key = this.key(bucketName, fileId);

    this.log.trace(`Uploading '${key}'`);

    const arrayBuffer = await file.arrayBuffer();

    await r2.put(key, arrayBuffer, {
      httpMetadata: {
        contentType: file.type,
      },
      customMetadata: {
        originalName: file.name,
        bucket: bucketName,
      },
    });

    return fileId;
  }

  public async download(bucketName: string, fileId: string): Promise<FileLike> {
    const r2 = this.getR2();
    const key = this.key(bucketName, fileId);

    this.log.trace(`Downloading '${key}'`);

    const object = await r2.get(key);
    if (!object) {
      throw new FileNotFoundError(
        `File '${fileId}' not found in bucket '${bucketName}'.`,
      );
    }

    const originalName = object.customMetadata?.originalName ?? fileId;
    const contentType =
      object.httpMetadata?.contentType ?? "application/octet-stream";

    return {
      name: originalName,
      type: contentType,
      size: object.size,
      lastModified: object.uploaded.getTime(),
      stream: () => object.body,
      arrayBuffer: () => object.arrayBuffer(),
      text: () => object.text(),
    };
  }

  public async exists(bucketName: string, fileId: string): Promise<boolean> {
    const r2 = this.getR2();
    const key = this.key(bucketName, fileId);

    this.log.trace(`Checking '${key}'`);

    const object = await r2.head(key);
    return object !== null;
  }

  public async delete(bucketName: string, fileId: string): Promise<void> {
    const r2 = this.getR2();
    const key = this.key(bucketName, fileId);

    this.log.trace(`Deleting '${key}'`);

    // R2's delete doesn't throw if the file doesn't exist,
    // so we check existence first for consistency with other providers
    const exists = await this.exists(bucketName, fileId);
    if (!exists) {
      throw new FileNotFoundError(
        `File '${fileId}' not found in bucket '${bucketName}'.`,
      );
    }

    await r2.delete(key);
  }

  /**
   * Build the full R2 key: {prefix}/{bucketName}/{fileId}
   */
  protected key(bucketName: string, fileId: string): string {
    const parts = [bucketName, fileId];
    if (this.prefix) {
      parts.unshift(this.prefix);
    }
    return parts.join("/");
  }

  protected getR2(): R2Bucket {
    if (!this.r2) {
      throw new AlephaError("R2 storage not initialized. Call start() first.");
    }
    return this.r2;
  }

  protected createId(filename: string): string {
    const ext = filename.includes(".") ? filename.split(".").pop() : "";
    const id = crypto.randomUUID();
    return ext ? `${id}.${ext}` : id;
  }
}
