import type { SeedData } from "./types.ts";

export const asiaSeeds: SeedData = {
  name: "Asia",
  stations: [
    // Japan
    { name: "Tokyo Station", code: "JPTYO", city: "Tokyo", country: "Japan" },
    { name: "Kyoto Station", code: "JPKYO", city: "Kyoto", country: "Japan" },
    { name: "Osaka Station", code: "JPOSA", city: "Osaka", country: "Japan" },
    {
      name: "Shin-Osaka Station",
      code: "JPSOS",
      city: "Osaka",
      country: "Japan",
    },
    { name: "Nagoya Station", code: "JPNGO", city: "Nagoya", country: "Japan" },
    {
      name: "Hiroshima Station",
      code: "JPHIR",
      city: "Hiroshima",
      country: "Japan",
    },
    // South Korea
    {
      name: "Seoul Station",
      code: "KRSEL",
      city: "Seoul",
      country: "South Korea",
    },
    {
      name: "Busan Station",
      code: "KRPUS",
      city: "Busan",
      country: "South Korea",
    },
    {
      name: "Daejeon Station",
      code: "KRDAE",
      city: "Daejeon",
      country: "South Korea",
    },
    // China
    { name: "Beijing South", code: "CNBJS", city: "Beijing", country: "China" },
    {
      name: "Shanghai Hongqiao",
      code: "CNSHA",
      city: "Shanghai",
      country: "China",
    },
    {
      name: "Guangzhou South",
      code: "CNCAN",
      city: "Guangzhou",
      country: "China",
    },
  ],
  trips: [
    // Tokyo - Kyoto (Tokaido Shinkansen)
    {
      from: "Tokyo Station",
      to: "Kyoto Station",
      departureTime: "06:00",
      arrivalTime: "08:15",
      duration: "2h 15min",
      trainNumber: "NZM 1",
      trainType: "Shinkansen Nozomi",
      basePrice: 125,
      availableSeats: 323,
    },
    {
      from: "Tokyo Station",
      to: "Kyoto Station",
      departureTime: "07:30",
      arrivalTime: "09:45",
      duration: "2h 15min",
      trainNumber: "NZM 5",
      trainType: "Shinkansen Nozomi",
      basePrice: 125,
      availableSeats: 289,
    },
    {
      from: "Tokyo Station",
      to: "Kyoto Station",
      departureTime: "09:00",
      arrivalTime: "11:15",
      duration: "2h 15min",
      trainNumber: "NZM 11",
      trainType: "Shinkansen Nozomi",
      basePrice: 125,
      availableSeats: 256,
    },
    {
      from: "Tokyo Station",
      to: "Kyoto Station",
      departureTime: "12:00",
      arrivalTime: "14:15",
      duration: "2h 15min",
      trainNumber: "NZM 21",
      trainType: "Shinkansen Nozomi",
      basePrice: 125,
      availableSeats: 198,
    },
    {
      from: "Kyoto Station",
      to: "Tokyo Station",
      departureTime: "08:00",
      arrivalTime: "10:15",
      duration: "2h 15min",
      trainNumber: "NZM 2",
      trainType: "Shinkansen Nozomi",
      basePrice: 125,
      availableSeats: 312,
    },
    {
      from: "Kyoto Station",
      to: "Tokyo Station",
      departureTime: "14:30",
      arrivalTime: "16:45",
      duration: "2h 15min",
      trainNumber: "NZM 32",
      trainType: "Shinkansen Nozomi",
      basePrice: 125,
      availableSeats: 245,
    },

    // Tokyo - Shin-Osaka
    {
      from: "Tokyo Station",
      to: "Shin-Osaka Station",
      departureTime: "06:30",
      arrivalTime: "09:03",
      duration: "2h 33min",
      trainNumber: "NZM 3",
      trainType: "Shinkansen Nozomi",
      basePrice: 135,
      availableSeats: 298,
    },
    {
      from: "Tokyo Station",
      to: "Shin-Osaka Station",
      departureTime: "10:00",
      arrivalTime: "12:33",
      duration: "2h 33min",
      trainNumber: "NZM 15",
      trainType: "Shinkansen Nozomi",
      basePrice: 135,
      availableSeats: 267,
    },
    {
      from: "Shin-Osaka Station",
      to: "Tokyo Station",
      departureTime: "07:00",
      arrivalTime: "09:33",
      duration: "2h 33min",
      trainNumber: "NZM 4",
      trainType: "Shinkansen Nozomi",
      basePrice: 135,
      availableSeats: 278,
    },

    // Tokyo - Nagoya
    {
      from: "Tokyo Station",
      to: "Nagoya Station",
      departureTime: "07:00",
      arrivalTime: "08:40",
      duration: "1h 40min",
      trainNumber: "NZM 7",
      trainType: "Shinkansen Nozomi",
      basePrice: 89,
      availableSeats: 345,
    },
    {
      from: "Tokyo Station",
      to: "Nagoya Station",
      departureTime: "11:00",
      arrivalTime: "12:40",
      duration: "1h 40min",
      trainNumber: "NZM 17",
      trainType: "Shinkansen Nozomi",
      basePrice: 89,
      availableSeats: 312,
    },
    {
      from: "Nagoya Station",
      to: "Tokyo Station",
      departureTime: "09:00",
      arrivalTime: "10:40",
      duration: "1h 40min",
      trainNumber: "NZM 8",
      trainType: "Shinkansen Nozomi",
      basePrice: 89,
      availableSeats: 298,
    },

    // Shin-Osaka - Hiroshima (Sanyo Shinkansen)
    {
      from: "Shin-Osaka Station",
      to: "Hiroshima Station",
      departureTime: "08:00",
      arrivalTime: "09:24",
      duration: "1h 24min",
      trainNumber: "NZM 101",
      trainType: "Shinkansen Nozomi",
      basePrice: 79,
      availableSeats: 256,
    },
    {
      from: "Shin-Osaka Station",
      to: "Hiroshima Station",
      departureTime: "13:00",
      arrivalTime: "14:24",
      duration: "1h 24min",
      trainNumber: "NZM 121",
      trainType: "Shinkansen Nozomi",
      basePrice: 79,
      availableSeats: 223,
    },
    {
      from: "Hiroshima Station",
      to: "Shin-Osaka Station",
      departureTime: "10:00",
      arrivalTime: "11:24",
      duration: "1h 24min",
      trainNumber: "NZM 102",
      trainType: "Shinkansen Nozomi",
      basePrice: 79,
      availableSeats: 267,
    },

    // Seoul - Busan (KTX)
    {
      from: "Seoul Station",
      to: "Busan Station",
      departureTime: "05:30",
      arrivalTime: "08:08",
      duration: "2h 38min",
      trainNumber: "KTX 101",
      trainType: "KTX",
      basePrice: 55,
      availableSeats: 410,
    },
    {
      from: "Seoul Station",
      to: "Busan Station",
      departureTime: "08:00",
      arrivalTime: "10:38",
      duration: "2h 38min",
      trainNumber: "KTX 111",
      trainType: "KTX",
      basePrice: 55,
      availableSeats: 378,
    },
    {
      from: "Seoul Station",
      to: "Busan Station",
      departureTime: "12:00",
      arrivalTime: "14:38",
      duration: "2h 38min",
      trainNumber: "KTX 131",
      trainType: "KTX",
      basePrice: 55,
      availableSeats: 345,
    },
    {
      from: "Seoul Station",
      to: "Busan Station",
      departureTime: "17:00",
      arrivalTime: "19:38",
      duration: "2h 38min",
      trainNumber: "KTX 151",
      trainType: "KTX",
      basePrice: 55,
      availableSeats: 289,
    },
    {
      from: "Busan Station",
      to: "Seoul Station",
      departureTime: "06:00",
      arrivalTime: "08:38",
      duration: "2h 38min",
      trainNumber: "KTX 102",
      trainType: "KTX",
      basePrice: 55,
      availableSeats: 398,
    },
    {
      from: "Busan Station",
      to: "Seoul Station",
      departureTime: "14:00",
      arrivalTime: "16:38",
      duration: "2h 38min",
      trainNumber: "KTX 142",
      trainType: "KTX",
      basePrice: 55,
      availableSeats: 356,
    },

    // Seoul - Daejeon
    {
      from: "Seoul Station",
      to: "Daejeon Station",
      departureTime: "07:00",
      arrivalTime: "07:50",
      duration: "0h 50min",
      trainNumber: "KTX 201",
      trainType: "KTX",
      basePrice: 25,
      availableSeats: 445,
    },
    {
      from: "Seoul Station",
      to: "Daejeon Station",
      departureTime: "10:00",
      arrivalTime: "10:50",
      duration: "0h 50min",
      trainNumber: "KTX 211",
      trainType: "KTX",
      basePrice: 25,
      availableSeats: 412,
    },
    {
      from: "Daejeon Station",
      to: "Seoul Station",
      departureTime: "08:00",
      arrivalTime: "08:50",
      duration: "0h 50min",
      trainNumber: "KTX 202",
      trainType: "KTX",
      basePrice: 25,
      availableSeats: 423,
    },

    // Beijing - Shanghai (China High-Speed Rail)
    {
      from: "Beijing South",
      to: "Shanghai Hongqiao",
      departureTime: "07:00",
      arrivalTime: "11:28",
      duration: "4h 28min",
      trainNumber: "G1",
      trainType: "CRH Fuxing",
      basePrice: 85,
      availableSeats: 556,
    },
    {
      from: "Beijing South",
      to: "Shanghai Hongqiao",
      departureTime: "09:00",
      arrivalTime: "13:28",
      duration: "4h 28min",
      trainNumber: "G5",
      trainType: "CRH Fuxing",
      basePrice: 85,
      availableSeats: 512,
    },
    {
      from: "Beijing South",
      to: "Shanghai Hongqiao",
      departureTime: "14:00",
      arrivalTime: "18:28",
      duration: "4h 28min",
      trainNumber: "G15",
      trainType: "CRH Fuxing",
      basePrice: 85,
      availableSeats: 478,
    },
    {
      from: "Shanghai Hongqiao",
      to: "Beijing South",
      departureTime: "08:00",
      arrivalTime: "12:28",
      duration: "4h 28min",
      trainNumber: "G2",
      trainType: "CRH Fuxing",
      basePrice: 85,
      availableSeats: 534,
    },
    {
      from: "Shanghai Hongqiao",
      to: "Beijing South",
      departureTime: "15:00",
      arrivalTime: "19:28",
      duration: "4h 28min",
      trainNumber: "G22",
      trainType: "CRH Fuxing",
      basePrice: 85,
      availableSeats: 489,
    },

    // Guangzhou - Shanghai
    {
      from: "Guangzhou South",
      to: "Shanghai Hongqiao",
      departureTime: "08:00",
      arrivalTime: "14:45",
      duration: "6h 45min",
      trainNumber: "G85",
      trainType: "CRH Fuxing",
      basePrice: 95,
      availableSeats: 498,
    },
    {
      from: "Shanghai Hongqiao",
      to: "Guangzhou South",
      departureTime: "09:00",
      arrivalTime: "15:45",
      duration: "6h 45min",
      trainNumber: "G86",
      trainType: "CRH Fuxing",
      basePrice: 95,
      availableSeats: 467,
    },

    // Beijing - Guangzhou
    {
      from: "Beijing South",
      to: "Guangzhou South",
      departureTime: "10:00",
      arrivalTime: "18:00",
      duration: "8h 00min",
      trainNumber: "G71",
      trainType: "CRH Fuxing",
      basePrice: 125,
      availableSeats: 423,
    },
    {
      from: "Guangzhou South",
      to: "Beijing South",
      departureTime: "08:00",
      arrivalTime: "16:00",
      duration: "8h 00min",
      trainNumber: "G72",
      trainType: "CRH Fuxing",
      basePrice: 125,
      availableSeats: 445,
    },
  ],
};
