import type { SeedData } from "./types.ts";

export const canadaSeeds: SeedData = {
  name: "Canada",
  stations: [
    // Ontario
    {
      name: "Toronto Union Station",
      code: "CATOR",
      city: "Toronto",
      country: "Canada",
    },
    {
      name: "Ottawa Station",
      code: "CAOTT",
      city: "Ottawa",
      country: "Canada",
    },
    {
      name: "Kingston Station",
      code: "CAKGS",
      city: "Kingston",
      country: "Canada",
    },
    {
      name: "London Station",
      code: "CALON",
      city: "London",
      country: "Canada",
    },
    {
      name: "Windsor Station",
      code: "CAWIN",
      city: "Windsor",
      country: "Canada",
    },
    // Quebec
    {
      name: "Montreal Central Station",
      code: "CAMTL",
      city: "Montreal",
      country: "Canada",
    },
    {
      name: "Quebec City Gare du Palais",
      code: "CAQUE",
      city: "Quebec City",
      country: "Canada",
    },
    // Western Canada
    {
      name: "Vancouver Pacific Central",
      code: "CAVAN",
      city: "Vancouver",
      country: "Canada",
    },
    {
      name: "Winnipeg Union Station",
      code: "CAWPG",
      city: "Winnipeg",
      country: "Canada",
    },
    {
      name: "Edmonton Station",
      code: "CAEDM",
      city: "Edmonton",
      country: "Canada",
    },
    // Atlantic Canada
    {
      name: "Halifax Station",
      code: "CAHAL",
      city: "Halifax",
      country: "Canada",
    },
  ],
  trips: [
    // The Corridor: Toronto - Montreal (most popular route)
    {
      from: "Toronto Union Station",
      to: "Montreal Central Station",
      departureTime: "06:40",
      arrivalTime: "11:24",
      duration: "4h 44min",
      trainNumber: "VIA 60",
      trainType: "VIA Corridor",
      basePrice: 49,
      availableSeats: 312,
    },
    {
      from: "Toronto Union Station",
      to: "Montreal Central Station",
      departureTime: "09:00",
      arrivalTime: "13:44",
      duration: "4h 44min",
      trainNumber: "VIA 64",
      trainType: "VIA Corridor",
      basePrice: 59,
      availableSeats: 267,
    },
    {
      from: "Toronto Union Station",
      to: "Montreal Central Station",
      departureTime: "12:00",
      arrivalTime: "16:44",
      duration: "4h 44min",
      trainNumber: "VIA 68",
      trainType: "VIA Corridor",
      basePrice: 69,
      availableSeats: 234,
    },
    {
      from: "Toronto Union Station",
      to: "Montreal Central Station",
      departureTime: "17:00",
      arrivalTime: "21:44",
      duration: "4h 44min",
      trainNumber: "VIA 72",
      trainType: "VIA Corridor",
      basePrice: 59,
      availableSeats: 198,
    },
    {
      from: "Montreal Central Station",
      to: "Toronto Union Station",
      departureTime: "07:00",
      arrivalTime: "11:44",
      duration: "4h 44min",
      trainNumber: "VIA 61",
      trainType: "VIA Corridor",
      basePrice: 49,
      availableSeats: 289,
    },
    {
      from: "Montreal Central Station",
      to: "Toronto Union Station",
      departureTime: "10:00",
      arrivalTime: "14:44",
      duration: "4h 44min",
      trainNumber: "VIA 65",
      trainType: "VIA Corridor",
      basePrice: 59,
      availableSeats: 245,
    },
    {
      from: "Montreal Central Station",
      to: "Toronto Union Station",
      departureTime: "16:00",
      arrivalTime: "20:44",
      duration: "4h 44min",
      trainNumber: "VIA 69",
      trainType: "VIA Corridor",
      basePrice: 69,
      availableSeats: 212,
    },

    // Toronto - Ottawa
    {
      from: "Toronto Union Station",
      to: "Ottawa Station",
      departureTime: "06:25",
      arrivalTime: "10:47",
      duration: "4h 22min",
      trainNumber: "VIA 40",
      trainType: "VIA Corridor",
      basePrice: 45,
      availableSeats: 278,
    },
    {
      from: "Toronto Union Station",
      to: "Ottawa Station",
      departureTime: "11:00",
      arrivalTime: "15:22",
      duration: "4h 22min",
      trainNumber: "VIA 44",
      trainType: "VIA Corridor",
      basePrice: 55,
      availableSeats: 234,
    },
    {
      from: "Toronto Union Station",
      to: "Ottawa Station",
      departureTime: "17:30",
      arrivalTime: "21:52",
      duration: "4h 22min",
      trainNumber: "VIA 48",
      trainType: "VIA Corridor",
      basePrice: 55,
      availableSeats: 189,
    },
    {
      from: "Ottawa Station",
      to: "Toronto Union Station",
      departureTime: "07:15",
      arrivalTime: "11:37",
      duration: "4h 22min",
      trainNumber: "VIA 41",
      trainType: "VIA Corridor",
      basePrice: 45,
      availableSeats: 267,
    },
    {
      from: "Ottawa Station",
      to: "Toronto Union Station",
      departureTime: "14:00",
      arrivalTime: "18:22",
      duration: "4h 22min",
      trainNumber: "VIA 45",
      trainType: "VIA Corridor",
      basePrice: 55,
      availableSeats: 223,
    },

    // Ottawa - Montreal
    {
      from: "Ottawa Station",
      to: "Montreal Central Station",
      departureTime: "06:35",
      arrivalTime: "08:32",
      duration: "1h 57min",
      trainNumber: "VIA 30",
      trainType: "VIA Corridor",
      basePrice: 35,
      availableSeats: 312,
    },
    {
      from: "Ottawa Station",
      to: "Montreal Central Station",
      departureTime: "12:15",
      arrivalTime: "14:12",
      duration: "1h 57min",
      trainNumber: "VIA 34",
      trainType: "VIA Corridor",
      basePrice: 39,
      availableSeats: 267,
    },
    {
      from: "Ottawa Station",
      to: "Montreal Central Station",
      departureTime: "18:00",
      arrivalTime: "19:57",
      duration: "1h 57min",
      trainNumber: "VIA 38",
      trainType: "VIA Corridor",
      basePrice: 39,
      availableSeats: 234,
    },
    {
      from: "Montreal Central Station",
      to: "Ottawa Station",
      departureTime: "07:45",
      arrivalTime: "09:42",
      duration: "1h 57min",
      trainNumber: "VIA 31",
      trainType: "VIA Corridor",
      basePrice: 35,
      availableSeats: 289,
    },
    {
      from: "Montreal Central Station",
      to: "Ottawa Station",
      departureTime: "15:30",
      arrivalTime: "17:27",
      duration: "1h 57min",
      trainNumber: "VIA 35",
      trainType: "VIA Corridor",
      basePrice: 39,
      availableSeats: 245,
    },

    // Montreal - Quebec City
    {
      from: "Montreal Central Station",
      to: "Quebec City Gare du Palais",
      departureTime: "07:15",
      arrivalTime: "10:28",
      duration: "3h 13min",
      trainNumber: "VIA 20",
      trainType: "VIA Corridor",
      basePrice: 39,
      availableSeats: 298,
    },
    {
      from: "Montreal Central Station",
      to: "Quebec City Gare du Palais",
      departureTime: "12:00",
      arrivalTime: "15:13",
      duration: "3h 13min",
      trainNumber: "VIA 24",
      trainType: "VIA Corridor",
      basePrice: 45,
      availableSeats: 256,
    },
    {
      from: "Montreal Central Station",
      to: "Quebec City Gare du Palais",
      departureTime: "17:30",
      arrivalTime: "20:43",
      duration: "3h 13min",
      trainNumber: "VIA 28",
      trainType: "VIA Corridor",
      basePrice: 45,
      availableSeats: 212,
    },
    {
      from: "Quebec City Gare du Palais",
      to: "Montreal Central Station",
      departureTime: "06:30",
      arrivalTime: "09:43",
      duration: "3h 13min",
      trainNumber: "VIA 21",
      trainType: "VIA Corridor",
      basePrice: 39,
      availableSeats: 278,
    },
    {
      from: "Quebec City Gare du Palais",
      to: "Montreal Central Station",
      departureTime: "14:00",
      arrivalTime: "17:13",
      duration: "3h 13min",
      trainNumber: "VIA 25",
      trainType: "VIA Corridor",
      basePrice: 45,
      availableSeats: 234,
    },

    // Toronto - Kingston
    {
      from: "Toronto Union Station",
      to: "Kingston Station",
      departureTime: "08:00",
      arrivalTime: "10:30",
      duration: "2h 30min",
      trainNumber: "VIA 650",
      trainType: "VIA Corridor",
      basePrice: 35,
      availableSeats: 312,
    },
    {
      from: "Toronto Union Station",
      to: "Kingston Station",
      departureTime: "14:00",
      arrivalTime: "16:30",
      duration: "2h 30min",
      trainNumber: "VIA 654",
      trainType: "VIA Corridor",
      basePrice: 39,
      availableSeats: 267,
    },
    {
      from: "Kingston Station",
      to: "Toronto Union Station",
      departureTime: "09:15",
      arrivalTime: "11:45",
      duration: "2h 30min",
      trainNumber: "VIA 651",
      trainType: "VIA Corridor",
      basePrice: 35,
      availableSeats: 289,
    },

    // Toronto - London - Windsor
    {
      from: "Toronto Union Station",
      to: "London Station",
      departureTime: "07:00",
      arrivalTime: "09:05",
      duration: "2h 05min",
      trainNumber: "VIA 70",
      trainType: "VIA Corridor",
      basePrice: 32,
      availableSeats: 298,
    },
    {
      from: "Toronto Union Station",
      to: "London Station",
      departureTime: "13:30",
      arrivalTime: "15:35",
      duration: "2h 05min",
      trainNumber: "VIA 74",
      trainType: "VIA Corridor",
      basePrice: 36,
      availableSeats: 256,
    },
    {
      from: "London Station",
      to: "Toronto Union Station",
      departureTime: "08:30",
      arrivalTime: "10:35",
      duration: "2h 05min",
      trainNumber: "VIA 71",
      trainType: "VIA Corridor",
      basePrice: 32,
      availableSeats: 278,
    },
    {
      from: "Toronto Union Station",
      to: "Windsor Station",
      departureTime: "07:00",
      arrivalTime: "11:05",
      duration: "4h 05min",
      trainNumber: "VIA 72",
      trainType: "VIA Corridor",
      basePrice: 52,
      availableSeats: 234,
    },
    {
      from: "Windsor Station",
      to: "Toronto Union Station",
      departureTime: "06:45",
      arrivalTime: "10:50",
      duration: "4h 05min",
      trainNumber: "VIA 73",
      trainType: "VIA Corridor",
      basePrice: 52,
      availableSeats: 212,
    },

    // The Canadian: Toronto - Vancouver (iconic scenic route)
    {
      from: "Toronto Union Station",
      to: "Vancouver Pacific Central",
      departureTime: "22:00",
      arrivalTime: "09:30",
      duration: "4 days",
      trainNumber: "VIA 1",
      trainType: "The Canadian",
      basePrice: 499,
      availableSeats: 156,
    },
    {
      from: "Vancouver Pacific Central",
      to: "Toronto Union Station",
      departureTime: "20:30",
      arrivalTime: "08:00",
      duration: "4 days",
      trainNumber: "VIA 2",
      trainType: "The Canadian",
      basePrice: 499,
      availableSeats: 156,
    },

    // The Canadian segments
    {
      from: "Toronto Union Station",
      to: "Winnipeg Union Station",
      departureTime: "22:00",
      arrivalTime: "08:00",
      duration: "1 day 10h",
      trainNumber: "VIA 1",
      trainType: "The Canadian",
      basePrice: 189,
      availableSeats: 167,
    },
    {
      from: "Winnipeg Union Station",
      to: "Edmonton Station",
      departureTime: "09:30",
      arrivalTime: "23:00",
      duration: "13h 30min",
      trainNumber: "VIA 1",
      trainType: "The Canadian",
      basePrice: 149,
      availableSeats: 178,
    },
    {
      from: "Edmonton Station",
      to: "Vancouver Pacific Central",
      departureTime: "00:30",
      arrivalTime: "09:30",
      duration: "1 day 9h",
      trainNumber: "VIA 1",
      trainType: "The Canadian",
      basePrice: 199,
      availableSeats: 145,
    },

    // Ocean: Montreal - Halifax
    {
      from: "Montreal Central Station",
      to: "Halifax Station",
      departureTime: "18:35",
      arrivalTime: "16:30",
      duration: "21h 55min",
      trainNumber: "VIA 14",
      trainType: "The Ocean",
      basePrice: 179,
      availableSeats: 134,
    },
    {
      from: "Halifax Station",
      to: "Montreal Central Station",
      departureTime: "12:35",
      arrivalTime: "10:30",
      duration: "21h 55min",
      trainNumber: "VIA 15",
      trainType: "The Ocean",
      basePrice: 179,
      availableSeats: 134,
    },
  ],
};
