import type { SeedData } from "./types.ts";

export const europeSeeds: SeedData = {
  name: "Europe",
  stations: [
    {
      name: "Paris Gare du Nord",
      code: "FRPNO",
      city: "Paris",
      country: "France",
    },
    {
      name: "London St Pancras",
      code: "GBSTP",
      city: "London",
      country: "United Kingdom",
    },
    {
      name: "Amsterdam Centraal",
      code: "NLAMC",
      city: "Amsterdam",
      country: "Netherlands",
    },
    {
      name: "Brussels Midi",
      code: "BEBMI",
      city: "Brussels",
      country: "Belgium",
    },
    {
      name: "Frankfurt Hbf",
      code: "DEFRA",
      city: "Frankfurt",
      country: "Germany",
    },
    { name: "Cologne Hbf", code: "DECGN", city: "Cologne", country: "Germany" },
    { name: "Lyon Part-Dieu", code: "FRLPD", city: "Lyon", country: "France" },
    {
      name: "Marseille Saint-Charles",
      code: "FRMSC",
      city: "Marseille",
      country: "France",
    },
    {
      name: "Barcelona Sants",
      code: "ESBCN",
      city: "Barcelona",
      country: "Spain",
    },
    { name: "Milan Centrale", code: "ITMIL", city: "Milan", country: "Italy" },
  ],
  trips: [
    // Paris - London
    {
      from: "Paris Gare du Nord",
      to: "London St Pancras",
      departureTime: "06:15",
      arrivalTime: "07:30",
      duration: "2h 15min",
      trainNumber: "EUR 9001",
      trainType: "Eurostar",
      basePrice: 89,
      availableSeats: 234,
    },
    {
      from: "Paris Gare du Nord",
      to: "London St Pancras",
      departureTime: "08:30",
      arrivalTime: "09:45",
      duration: "2h 15min",
      trainNumber: "EUR 9005",
      trainType: "Eurostar",
      basePrice: 109,
      availableSeats: 189,
    },
    {
      from: "Paris Gare du Nord",
      to: "London St Pancras",
      departureTime: "12:00",
      arrivalTime: "13:15",
      duration: "2h 15min",
      trainNumber: "EUR 9021",
      trainType: "Eurostar",
      basePrice: 149,
      availableSeats: 156,
    },
    {
      from: "Paris Gare du Nord",
      to: "London St Pancras",
      departureTime: "17:15",
      arrivalTime: "18:30",
      duration: "2h 15min",
      trainNumber: "EUR 9041",
      trainType: "Eurostar",
      basePrice: 129,
      availableSeats: 98,
    },
    {
      from: "London St Pancras",
      to: "Paris Gare du Nord",
      departureTime: "07:00",
      arrivalTime: "10:15",
      duration: "2h 15min",
      trainNumber: "EUR 9002",
      trainType: "Eurostar",
      basePrice: 89,
      availableSeats: 212,
    },
    {
      from: "London St Pancras",
      to: "Paris Gare du Nord",
      departureTime: "14:00",
      arrivalTime: "17:15",
      duration: "2h 15min",
      trainNumber: "EUR 9022",
      trainType: "Eurostar",
      basePrice: 119,
      availableSeats: 167,
    },

    // Paris - Amsterdam
    {
      from: "Paris Gare du Nord",
      to: "Amsterdam Centraal",
      departureTime: "06:45",
      arrivalTime: "10:03",
      duration: "3h 18min",
      trainNumber: "THA 9301",
      trainType: "Thalys",
      basePrice: 79,
      availableSeats: 142,
    },
    {
      from: "Paris Gare du Nord",
      to: "Amsterdam Centraal",
      departureTime: "10:30",
      arrivalTime: "13:48",
      duration: "3h 18min",
      trainNumber: "THA 9311",
      trainType: "Thalys",
      basePrice: 99,
      availableSeats: 89,
    },
    {
      from: "Amsterdam Centraal",
      to: "Paris Gare du Nord",
      departureTime: "08:00",
      arrivalTime: "11:18",
      duration: "3h 18min",
      trainNumber: "THA 9302",
      trainType: "Thalys",
      basePrice: 79,
      availableSeats: 156,
    },

    // Paris - Brussels
    {
      from: "Paris Gare du Nord",
      to: "Brussels Midi",
      departureTime: "07:00",
      arrivalTime: "08:22",
      duration: "1h 22min",
      trainNumber: "THA 9101",
      trainType: "Thalys",
      basePrice: 49,
      availableSeats: 198,
    },
    {
      from: "Paris Gare du Nord",
      to: "Brussels Midi",
      departureTime: "12:30",
      arrivalTime: "13:52",
      duration: "1h 22min",
      trainNumber: "THA 9121",
      trainType: "Thalys",
      basePrice: 59,
      availableSeats: 145,
    },
    {
      from: "Brussels Midi",
      to: "Paris Gare du Nord",
      departureTime: "09:00",
      arrivalTime: "10:22",
      duration: "1h 22min",
      trainNumber: "THA 9102",
      trainType: "Thalys",
      basePrice: 49,
      availableSeats: 167,
    },

    // Frankfurt - Cologne
    {
      from: "Frankfurt Hbf",
      to: "Cologne Hbf",
      departureTime: "06:30",
      arrivalTime: "07:35",
      duration: "1h 05min",
      trainNumber: "ICE 101",
      trainType: "ICE",
      basePrice: 39,
      availableSeats: 234,
    },
    {
      from: "Frankfurt Hbf",
      to: "Cologne Hbf",
      departureTime: "09:15",
      arrivalTime: "10:20",
      duration: "1h 05min",
      trainNumber: "ICE 111",
      trainType: "ICE",
      basePrice: 45,
      availableSeats: 189,
    },
    {
      from: "Frankfurt Hbf",
      to: "Cologne Hbf",
      departureTime: "14:00",
      arrivalTime: "15:05",
      duration: "1h 05min",
      trainNumber: "ICE 131",
      trainType: "ICE",
      basePrice: 49,
      availableSeats: 156,
    },
    {
      from: "Cologne Hbf",
      to: "Frankfurt Hbf",
      departureTime: "08:00",
      arrivalTime: "09:05",
      duration: "1h 05min",
      trainNumber: "ICE 102",
      trainType: "ICE",
      basePrice: 39,
      availableSeats: 212,
    },
    {
      from: "Cologne Hbf",
      to: "Frankfurt Hbf",
      departureTime: "16:30",
      arrivalTime: "17:35",
      duration: "1h 05min",
      trainNumber: "ICE 142",
      trainType: "ICE",
      basePrice: 45,
      availableSeats: 178,
    },

    // Lyon - Marseille
    {
      from: "Lyon Part-Dieu",
      to: "Marseille Saint-Charles",
      departureTime: "07:00",
      arrivalTime: "08:40",
      duration: "1h 40min",
      trainNumber: "TGV 6201",
      trainType: "TGV INOUI",
      basePrice: 45,
      availableSeats: 312,
    },
    {
      from: "Lyon Part-Dieu",
      to: "Marseille Saint-Charles",
      departureTime: "12:15",
      arrivalTime: "13:55",
      duration: "1h 40min",
      trainNumber: "TGV 6221",
      trainType: "TGV INOUI",
      basePrice: 55,
      availableSeats: 256,
    },
    {
      from: "Marseille Saint-Charles",
      to: "Lyon Part-Dieu",
      departureTime: "09:30",
      arrivalTime: "11:10",
      duration: "1h 40min",
      trainNumber: "TGV 6202",
      trainType: "TGV INOUI",
      basePrice: 45,
      availableSeats: 289,
    },

    // Amsterdam - Brussels
    {
      from: "Amsterdam Centraal",
      to: "Brussels Midi",
      departureTime: "06:00",
      arrivalTime: "07:50",
      duration: "1h 50min",
      trainNumber: "THA 9201",
      trainType: "Thalys",
      basePrice: 49,
      availableSeats: 167,
    },
    {
      from: "Amsterdam Centraal",
      to: "Brussels Midi",
      departureTime: "11:00",
      arrivalTime: "12:50",
      duration: "1h 50min",
      trainNumber: "THA 9211",
      trainType: "Thalys",
      basePrice: 59,
      availableSeats: 134,
    },
    {
      from: "Brussels Midi",
      to: "Amsterdam Centraal",
      departureTime: "08:30",
      arrivalTime: "10:20",
      duration: "1h 50min",
      trainNumber: "THA 9202",
      trainType: "Thalys",
      basePrice: 49,
      availableSeats: 189,
    },

    // Paris - Lyon
    {
      from: "Paris Gare du Nord",
      to: "Lyon Part-Dieu",
      departureTime: "06:00",
      arrivalTime: "08:00",
      duration: "2h 00min",
      trainNumber: "TGV 6001",
      trainType: "TGV INOUI",
      basePrice: 59,
      availableSeats: 345,
    },
    {
      from: "Paris Gare du Nord",
      to: "Lyon Part-Dieu",
      departureTime: "10:00",
      arrivalTime: "12:00",
      duration: "2h 00min",
      trainNumber: "TGV 6011",
      trainType: "TGV INOUI",
      basePrice: 79,
      availableSeats: 267,
    },
    {
      from: "Lyon Part-Dieu",
      to: "Paris Gare du Nord",
      departureTime: "07:30",
      arrivalTime: "09:30",
      duration: "2h 00min",
      trainNumber: "TGV 6002",
      trainType: "TGV INOUI",
      basePrice: 59,
      availableSeats: 298,
    },

    // Milan - Paris (via Lyon)
    {
      from: "Milan Centrale",
      to: "Paris Gare du Nord",
      departureTime: "06:30",
      arrivalTime: "13:45",
      duration: "7h 15min",
      trainNumber: "TGV 9241",
      trainType: "TGV INOUI",
      basePrice: 129,
      availableSeats: 156,
    },
    {
      from: "Paris Gare du Nord",
      to: "Milan Centrale",
      departureTime: "07:00",
      arrivalTime: "14:15",
      duration: "7h 15min",
      trainNumber: "TGV 9242",
      trainType: "TGV INOUI",
      basePrice: 129,
      availableSeats: 178,
    },

    // Barcelona - Paris
    {
      from: "Barcelona Sants",
      to: "Paris Gare du Nord",
      departureTime: "08:00",
      arrivalTime: "14:30",
      duration: "6h 30min",
      trainNumber: "AVE 9701",
      trainType: "AVE",
      basePrice: 119,
      availableSeats: 189,
    },
    {
      from: "Paris Gare du Nord",
      to: "Barcelona Sants",
      departureTime: "09:30",
      arrivalTime: "16:00",
      duration: "6h 30min",
      trainNumber: "AVE 9702",
      trainType: "AVE",
      basePrice: 119,
      availableSeats: 212,
    },
  ],
};
