import { $inject, Alepha, type Static } from "alepha";
import {
  ssrManifestAtom,
  type SsrManifestAtomSchema,
} from "../atoms/ssrManifestAtom.ts";

/**
 * SSR Manifest structure from Vite.
 * Maps source file paths to their required chunks/assets.
 */
export type SSRManifest = Record<string, string[]>;

/**
 * Client manifest structure from Vite.
 * Maps source files to their output information.
 */
export interface ClientManifest {
  [key: string]: {
    file: string;
    src?: string;
    isEntry?: boolean;
    isDynamicEntry?: boolean;
    imports?: string[];
    dynamicImports?: string[];
    css?: string[];
    assets?: string[];
  };
}

/**
 * Preload manifest mapping short keys to source paths.
 * Generated by viteAlephaSsrPreload plugin at build time.
 */
export type PreloadManifest = Record<string, string>;

/**
 * Provider for SSR manifest data used for module preloading.
 *
 * The manifest is populated at build time by embedding data into the
 * generated index.js via the ssrManifestAtom. This eliminates filesystem
 * reads at runtime, making it optimal for serverless deployments.
 *
 * Manifest files are generated during `vite build`:
 * - manifest.json (client manifest)
 * - ssr-manifest.json (SSR manifest)
 * - preload-manifest.json (from viteAlephaSsrPreload plugin)
 */
export class SSRManifestProvider {
  protected readonly alepha = $inject(Alepha);

  /**
   * Get the manifest from the store at runtime.
   * This ensures the manifest is available even when set after module load.
   */
  protected get manifest(): Static<SsrManifestAtomSchema> {
    return (this.alepha.store.get(ssrManifestAtom) as Static<SsrManifestAtomSchema>) ?? {};
  }

  /**
   * Get the preload manifest.
   */
  protected get preloadManifest(): PreloadManifest | undefined {
    return this.manifest.preload;
  }

  /**
   * Get the SSR manifest.
   */
  protected get ssrManifest(): SSRManifest | undefined {
    return this.manifest.ssr;
  }

  /**
   * Get the client manifest.
   */
  protected get clientManifest(): ClientManifest | undefined {
    return this.manifest.client;
  }

  /**
   * Resolve a preload key to its source path.
   *
   * The key is a short hash injected by viteAlephaSsrPreload plugin,
   * which maps to the full source path in the preload manifest.
   *
   * @param key - Short hash key (e.g., "a1b2c3d4")
   * @returns Source path (e.g., "src/pages/UserDetail.tsx") or undefined
   */
  public resolvePreloadKey(key: string): string | undefined {
    return this.preloadManifest?.[key];
  }

  /**
   * Get all chunks required for a source file, including transitive dependencies.
   *
   * Uses the client manifest to recursively resolve all imported chunks,
   * not just the direct chunks from the SSR manifest.
   *
   * @param sourcePath - Source file path (e.g., "src/pages/Home.tsx")
   * @returns Array of chunk URLs to preload, or empty array if not found
   */
  public getChunks(sourcePath: string): string[] {
    if (!this.clientManifest) {
      // Fallback to SSR manifest if client manifest not available
      return this.getChunksFromSSRManifest(sourcePath);
    }

    // Find entry in client manifest
    const entry = this.findManifestEntry(sourcePath);
    if (!entry) {
      return [];
    }

    // Recursively collect all chunks
    const chunks = new Set<string>();
    const visited = new Set<string>();

    this.collectChunksRecursive(sourcePath, chunks, visited);

    return Array.from(chunks);
  }

  /**
   * Find manifest entry for a source path, trying different extensions.
   */
  protected findManifestEntry(sourcePath: string) {
    if (!this.clientManifest) return undefined;

    // Try exact match
    if (this.clientManifest[sourcePath]) {
      return this.clientManifest[sourcePath];
    }

    // Try with different extensions
    const basePath = sourcePath.replace(/\.[^.]+$/, "");
    for (const ext of [".tsx", ".ts", ".jsx", ".js"]) {
      const pathWithExt = basePath + ext;
      if (this.clientManifest[pathWithExt]) {
        return this.clientManifest[pathWithExt];
      }
    }

    return undefined;
  }

  /**
   * Recursively collect all chunk URLs for a manifest entry.
   */
  protected collectChunksRecursive(
    key: string,
    chunks: Set<string>,
    visited: Set<string>,
  ): void {
    if (visited.has(key)) return;
    visited.add(key);

    if (!this.clientManifest) return;

    const entry = this.clientManifest[key];
    if (!entry) return;

    // Add main chunk file (with leading slash for URL)
    if (entry.file) {
      chunks.add("/" + entry.file);
    }

    // Add CSS files
    if (entry.css) {
      for (const css of entry.css) {
        chunks.add("/" + css);
      }
    }

    // Recursively process imports (but skip entry point)
    if (entry.imports) {
      for (const imp of entry.imports) {
        // Skip the main entry point (index.html) - it's already being loaded
        if (imp === "index.html" || imp.endsWith(".html")) {
          continue;
        }
        this.collectChunksRecursive(imp, chunks, visited);
      }
    }

    // Note: We intentionally do NOT follow dynamicImports
    // Those are lazy-loaded and shouldn't be preloaded
  }

  /**
   * Fallback to SSR manifest for chunk lookup.
   */
  protected getChunksFromSSRManifest(sourcePath: string): string[] {
    if (!this.ssrManifest) {
      return [];
    }

    // Try exact match
    if (this.ssrManifest[sourcePath]) {
      return this.ssrManifest[sourcePath];
    }

    // Try with different extensions
    const basePath = sourcePath.replace(/\.[^.]+$/, "");
    for (const ext of [".tsx", ".ts", ".jsx", ".js"]) {
      const pathWithExt = basePath + ext;
      if (this.ssrManifest[pathWithExt]) {
        return this.ssrManifest[pathWithExt];
      }
    }

    return [];
  }

  /**
   * Get modulepreload links for a source file.
   *
   * @param sourcePath - Source file path
   * @returns Array of objects with rel and href for link tags
   */
  public getPreloadLinks(
    sourcePath: string,
  ): Array<{ rel: string; href: string; as?: string; crossorigin?: string }> {
    const chunks = this.getChunks(sourcePath);

    return chunks.map((href) => {
      // Determine if it's JS or CSS
      if (href.endsWith(".css")) {
        return {
          rel: "preload",
          href,
          as: "style",
        };
      }

      return {
        rel: "modulepreload",
        href,
      };
    });
  }

  /**
   * Get all chunks for multiple source files.
   *
   * @param sourcePaths - Array of source file paths
   * @returns Deduplicated array of chunk URLs
   */
  public getChunksForMultiple(sourcePaths: string[]): string[] {
    const allChunks = new Set<string>();

    for (const path of sourcePaths) {
      const chunks = this.getChunks(path);
      for (const chunk of chunks) {
        allChunks.add(chunk);
      }
    }

    return Array.from(allChunks);
  }

  /**
   * Check if manifests are loaded and available.
   */
  public isAvailable(): boolean {
    return this.clientManifest !== undefined || this.ssrManifest !== undefined;
  }
}
