import { $atom, t } from "alepha";

/**
 * Schema for the SSR manifest atom.
 */
export const ssrManifestAtomSchema = t.object({
  /**
   * Preload manifest mapping short keys to source paths.
   * Generated by viteAlephaSsrPreload plugin at build time.
   */
  preload: t.optional(t.record(t.string(), t.string())),

  /**
   * SSR manifest mapping source files to their required chunks.
   */
  ssr: t.optional(t.record(t.string(), t.array(t.string()))),

  /**
   * Client manifest mapping source files to their output information.
   */
  client: t.optional(
    t.record(
      t.string(),
      t.object({
        file: t.string(),
        src: t.optional(t.string()),
        isEntry: t.optional(t.boolean()),
        isDynamicEntry: t.optional(t.boolean()),
        imports: t.optional(t.array(t.string())),
        dynamicImports: t.optional(t.array(t.string())),
        css: t.optional(t.array(t.string())),
        assets: t.optional(t.array(t.string())),
      }),
    ),
  ),
});

/**
 * Type for the SSR manifest schema.
 */
export type SsrManifestAtomSchema = typeof ssrManifestAtomSchema;

/**
 * SSR Manifest atom containing all manifest data for SSR module preloading.
 *
 * This atom is populated at build time by embedding manifest data into the
 * generated index.js. This approach is optimal for serverless deployments
 * as it eliminates filesystem reads at runtime.
 *
 * The manifest includes:
 * - preload: Maps short hash keys to source paths (from viteAlephaSsrPreload)
 * - ssr: Maps source files to their required chunks
 * - client: Maps source files to their output info including imports/css
 */
export const ssrManifestAtom = $atom({
  name: "alepha.react.ssr.manifest",
  description: "SSR manifest for module preloading",
  schema: ssrManifestAtomSchema,
  default: {},
});
