import { capacitor } from "@alepha/capacitor/cli";
import { defineConfig } from "alepha/cli/config";

/**
 * The test bed of `@alepha/capacitor`: see README.md.
 *
 * `apiUrl` is the API the native shell calls. It differs per machine (a LAN
 * address for a phone, an e2e port in CI), so it comes from the environment:
 * `MOBILE_API_URL=https://192.168.1.48:8443 yarn alepha capacitor sync --variant base`.
 *
 * `acme` is a second installable app from the same code, a branded build:
 * its own bundle id, name, scheme, icon and API. With a variant declared,
 * every command names one: `--variant acme`, or `--variant base`.
 */
export default defineConfig({
  dev: { port: 3313 },
  plugins: [
    capacitor({
      appId: "dev.alepha.mobile",
      appName: "Alepha Mobile",
      scheme: "alephamobile",
      apiUrl: process.env.MOBILE_API_URL,
      // Icons and splash for both native projects, generated by init.
      icon: { source: "public/favicon.svg", background: "#FFFFFF" },
      variants: {
        acme: {
          appId: "dev.alepha.mobile.acme",
          appName: "Acme Notes",
          scheme: "acmenotes",
          apiUrl: process.env.MOBILE_ACME_API_URL,
          icon: { source: "variants/acme.svg", background: "#0F172A" },
        },
      },
    }),
  ],
});
