// Generated by `alepha capacitor` from alepha.config.ts.
// Change capacitor({ ... }) there: the next command rewrites this file.
import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "dev.alepha.mobile",
  appName: "Alepha Mobile",
  webDir: "dist-capacitor/base/public",
  plugins: {
    SplashScreen: {
      launchAutoHide: true,
      launchShowDuration: 8000,
    },
    CapacitorUpdater: {
      autoUpdate: false,
      updateUrl: "",
      statsUrl: "",
      channelUrl: "",
    },
  },
};

export default config;
