import { defineConfig } from "alepha/cli/config";
import { devtools } from "alepha/cli/devtools";
import { platform } from "alepha/cli/platform";

export default defineConfig({
  // Dev ports live in the 33xx band, which `playwright.port.ts` keeps strictly
  // DISJOINT from the 4300-4999 e2e band. The two used to be the same number,
  // and a running `yarn dev` was then adopted by the e2e suite. Every app
  // without a `dev.port` binds 5173.
  dev: { port: 3305 },
  plugins: [
    /*
     * Dev-server only: the plugin is registered by the CLI, never by the app, so
     * nothing here reaches the deployed Worker. It mounts the inspector at
     * `/__devtools/` and injects the floating button into every dev page.
     */
    devtools(),
    platform({
      /*
       * Deployed through Lore by CI (`deploy-shop-production`), never from
       * here: the variables live in the `shop / production` copy's Environment
       * tab. `APP_SECRET` is minted there on the first deploy; `SIGIL_KEY`,
       * `STRIPE_SECRET_KEY` and `STRIPE_WEBHOOK_SECRET` are set by hand.
       *
       * D1 and R2 bindings are generated by the build — the catalogue's drawings
       * go to R2 through `$storage`, and the database is D1, which is why the
       * migrations under `migrations/sqlite/` are already the right dialect.
       */
      environments: {
        production: {
          domain: "shop.alepha.dev",
          adapter: "cloudflare",
        },
      },
    }),
  ],
});
