import { defineConfig } from "alepha/cli/config";
import { platform } from "alepha/cli/platform";

export default defineConfig({
  plugins: [
    platform({
      /*
       * Worker secrets are auto-detected from the build manifest's `env` list
       * (every `$env`-declared key) and resolved from `process.env` at deploy
       * time, so there is no `secrets.keys` to maintain here. In practice this
       * app needs exactly one that has no safe default: `APP_SECRET`, which
       * Alepha refuses to boot without in production. It lives in
       * `.env.production`, which is gitignored.
       *
       * D1 and R2 bindings are generated by the build — the catalogue's drawings
       * go to R2 through `$storage`, and the database is D1, which is why the
       * migrations under `migrations/sqlite/` are already the right dialect.
       */
      environments: {
        production: {
          domain: "shop.alepha.dev",
          adapter: "cloudflare",
        },
      },
    }),
  ],
});
