import { isAbsolute, normalize } from "node:path";
import { fileURLToPath } from "node:url";

import { AlephaError } from "alepha";
import type { FileSystemProvider, ShellProvider } from "alepha/system";

import {
  type DesktopConfig,
  desktopConfigSchema,
} from "../core/schemas/desktopConfigSchema.ts";

/**
 * The three entries `alepha compile --desktop` compiles into one executable.
 */
export interface DesktopEntryNames {
  shell: string;
  supervisor: string;
  worker: string;
}

/**
 * The `@alepha/desktop` side of `alepha compile --desktop`.
 *
 * `alepha` resolves this class from the app's own dependencies and calls it
 * with the CLI's file system and shell (`DesktopAdapter` in `alepha/cli`):
 *
 * 1. {@link preflight}: the config against `desktopConfigSchema`, the icon,
 *    and the macOS tools the bundle needs, before `dist/` is touched;
 * 2. {@link writeEntries}: the generated shell, supervisor and server Worker
 *    entries, written into the staged `dist/`;
 * 3. {@link assemble}: the compiled executable into the final artifact.
 *
 * The generated entries import this package by absolute path, resolved from
 * where it is installed, so they resolve the same `@alepha/desktop` (and its
 * `webview-bun`) wherever the staging directory is.
 */
export class DesktopCompileAdapter {
  protected readonly fs: FileSystemProvider;
  protected readonly shell: ShellProvider;

  /**
   * The generated entry files, the shell first.
   */
  public readonly entries: DesktopEntryNames = {
    shell: "desktop-shell.js",
    supervisor: "desktop-supervisor.js",
    worker: "desktop-worker.js",
  };

  /**
   * The macOS tools the bundle is built with.
   */
  public readonly tools = ["codesign", "sips", "iconutil"];

  constructor(services: { fs: FileSystemProvider; shell: ShellProvider }) {
    this.fs = services.fs;
    this.shell = services.shell;
  }

  public async preflight(input: {
    root: string;
    config: unknown;
    target: string;
  }): Promise<DesktopConfig> {
    const parsed = desktopConfigSchema.safeParse(input.config);
    if (!parsed.success) {
      const issues = parsed.error.issues
        .map((issue) => `desktop.${issue.path.join(".")}: ${issue.message}`)
        .join("; ");
      throw new AlephaError(
        `Invalid desktop config in alepha.config.ts: ${issues}`,
      );
    }
    const config = parsed.data;

    if (config.icon) {
      const icon = normalize(config.icon);
      if (isAbsolute(icon) || icon.startsWith("..")) {
        throw new AlephaError(
          `desktop.icon must be a path inside the project, relative to its root (got '${config.icon}').`,
        );
      }
      if (!icon.toLowerCase().endsWith(".png")) {
        throw new AlephaError(
          `desktop.icon must be a PNG (got '${config.icon}').`,
        );
      }
      if (!(await this.fs.exists(this.fs.join(input.root, icon)))) {
        throw new AlephaError(`desktop.icon '${config.icon}' does not exist.`);
      }
    }

    const missing: string[] = [];
    for (const tool of this.tools) {
      if (!(await this.shell.isInstalled(tool))) {
        missing.push(tool);
      }
    }
    if (missing.length > 0) {
      throw new AlephaError(
        `alepha compile --desktop needs ${missing.join(", ")}, which macOS ships with Xcode's command line tools: run \`xcode-select --install\`.`,
      );
    }

    return config;
  }

  public async writeEntries(input: {
    dist: string;
    config: DesktopConfig;
  }): Promise<string[]> {
    const shell = JSON.stringify(this.modulePath("shell"));
    const worker = JSON.stringify(this.modulePath("worker"));
    const header =
      "// Generated by `alepha compile --desktop`. Compiled into the app, never kept.\n";

    await this.fs.writeFile(
      this.fs.join(input.dist, this.entries.shell),
      `${header}import { DesktopMain } from ${shell};\n\n` +
        "await new DesktopMain().run({\n" +
        `  config: ${JSON.stringify(input.config)},\n` +
        `  workerUrl: new URL("./${this.entries.worker}", import.meta.url).href,\n` +
        `  supervisorUrl: new URL("./${this.entries.supervisor}", import.meta.url).href,\n` +
        "});\n",
    );
    await this.fs.writeFile(
      this.fs.join(input.dist, this.entries.supervisor),
      `${header}import { DesktopSupervisorWorker, NativeLoopTerminator } from ${shell};\n\n` +
        "const terminator = new NativeLoopTerminator();\n" +
        "new DesktopSupervisorWorker(self, (handle) => terminator.terminate(handle)).listen();\n" +
        "void terminator.load();\n",
    );
    await this.fs.writeFile(
      this.fs.join(input.dist, this.entries.worker),
      `${header}import { DesktopWorkerHost } from ${worker};\n\n` +
        'new DesktopWorkerHost(self, () => import("./index.bun.js")).listen();\n',
    );

    return [this.entries.shell, this.entries.supervisor, this.entries.worker];
  }

  public async assemble(input: {
    root: string;
    stage: string;
    dist: string;
    binary: string;
    name: string;
    config: DesktopConfig;
  }): Promise<string> {
    const target = this.fs.join(input.stage, input.name);
    await this.fs.cp(input.binary, target);
    return target;
  }

  /**
   * The absolute path of one of this package's entries, in the same form
   * (source or built) as this file.
   */
  protected modulePath(entry: "shell" | "worker"): string {
    const ext = import.meta.url.endsWith(".ts") ? ".ts" : ".js";
    return fileURLToPath(new URL(`../${entry}/index${ext}`, import.meta.url));
  }
}
