import { $atom, t } from "alepha";

/**
 * Schema for the SSR manifest atom.
 */
export const ssrManifestAtomSchema = t.object({
  /**
   * Base path for assets (from Vite's base config).
   * Used to prefix asset URLs when serving from a subpath.
   * @example "/devtools" or "/"
   */
  base: t.optional(t.string()),

  /**
   * Preload manifest mapping short keys to source paths.
   * Generated by viteAlephaSsrPreload plugin at build time.
   */
  preload: t.optional(t.record(t.string(), t.string())),

  /**
   * Client manifest mapping source files to their output information.
   * Only includes fields actually used for preloading.
   */
  client: t.optional(
    t.record(
      t.string(),
      t.object({
        file: t.string(),
        isEntry: t.optional(t.boolean()),
        imports: t.optional(t.array(t.string())),
        css: t.optional(t.array(t.string())),
      }),
    ),
  ),

  /**
   * Dev mode head content.
   * Contains pre-transformed scripts injected by Vite and plugins (React, etc.).
   * Only set in dev mode via ViteDevServerProvider.
   */
  devHead: t.optional(t.string()),

  /**
   * Auto-detected favicon path and MIME type.
   * Format: "type:path" (e.g., "image/svg+xml:/favicon.svg").
   * Set at build/dev time by scanning the public directory.
   */
  favicon: t.optional(t.string()),
});

/**
 * Type for the SSR manifest schema.
 */
export type SsrManifestAtomSchema = typeof ssrManifestAtomSchema;

/**
 * SSR Manifest atom containing all manifest data for SSR module preloading.
 *
 * This atom is populated at build time by embedding manifest data into the
 * generated index.js. This approach is optimal for serverless deployments
 * as it eliminates filesystem reads at runtime.
 *
 * The manifest includes:
 * - preload: Maps short hash keys to source paths (from viteAlephaSsrPreload)
 * - client: Maps source files to their output info (file, imports, css)
 */
export const ssrManifestAtom = $atom({
  name: "alepha.react.ssr.manifest",
  description: "SSR manifest for module preloading",
  schema: ssrManifestAtomSchema,
  default: {},
});
