import { $inject, Alepha, AlephaError } from "alepha";
import type { ContainerPrimitive } from "../primitives/$container.ts";
import {
  type ContainerInvokeConfig,
  ContainerProvider,
} from "./ContainerProvider.ts";

/**
 * Cloudflare Workers (workerd) container provider.
 *
 * Routes proxy calls through the Cloudflare Containers binding bound on
 * `env.<NAME>`, using a single shared instance per container
 * (`getContainer(env.NAME, "shared")`). The binding is generated by
 * `BuildCloudflareTask.enhanceContainers` from the `$container`
 * primitives discovered in the app.
 *
 * The runtime `env` object is pulled from the Alepha store key
 * `cloudflare.env` — the worker entry point publishes it there on every
 * fetch (`__alepha.set("cloudflare.env", env)`).
 */
export class CloudflareContainerProvider extends ContainerProvider {
  protected readonly alepha = $inject(Alepha);

  public override async invoke(
    container: ContainerPrimitive,
    action: string,
    config: ContainerInvokeConfig,
  ): Promise<unknown> {
    const env = this.alepha.store.get("cloudflare.env") as
      | Record<string, unknown>
      | undefined;
    if (!env) {
      throw new AlephaError(
        `CloudflareContainerProvider could not resolve 'cloudflare.env' from the store — is the app running on workerd?`,
      );
    }

    const binding = env[container.name.toUpperCase()] as
      | {
          getContainer?: (id: string) => {
            fetch(req: Request): Promise<Response>;
          };
        }
      | undefined;

    if (!binding?.getContainer) {
      throw new AlephaError(
        `Cloudflare Containers binding '${container.name.toUpperCase()}' not found on env — check wrangler.jsonc.`,
      );
    }

    const instance = binding.getContainer("shared");
    const { path, init } = this.buildRequest(action, config);
    const request = new Request(`http://container${path}`, init);
    const response = await instance.fetch(request);

    if (!response.ok) {
      const text = await response.text().catch(() => "");
      throw new AlephaError(
        `Container '${container.name}' action '${action}' failed: ${response.status} ${response.statusText}${
          text ? ` — ${text}` : ""
        }`,
      );
    }

    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.includes("application/json")) {
      return await response.json();
    }
    return await response.text();
  }
}
