import { $inject, $store, Alepha, AlephaError } from "alepha";
import { FileSystemProvider } from "alepha/system";

import type { CapacitorPublicConfig } from "../../core/schemas/capacitorPublicConfigSchema.ts";
import {
  type CapacitorOptions,
  type CapacitorPlatform,
  capacitorOptions,
} from "../atoms/capacitorOptions.ts";

/**
 * Where everything of a native app lives, and the files the plugin owns.
 *
 * One place for the paths every `alepha capacitor` command shares: the
 * generated `capacitor.config.ts`, the shell's output directory, the two
 * native projects and the files inside them the plugin edits.
 */
export class CapacitorProject {
  /**
   * The first line of every file the plugin generates. A file that carries it
   * is the plugin's to rewrite; one that does not belongs to the user.
   */
  public static readonly GENERATED_MARKER =
    "// Generated by `alepha capacitor` from alepha.config.ts.";

  /**
   * The shell's build output, apart from the server's `dist/` so a native
   * build never moves a web deploy.
   */
  public static readonly DIST_DIR = "dist-capacitor";

  /**
   * The directory Capacitor copies into the native projects.
   */
  public static readonly WEB_DIR = `${CapacitorProject.DIST_DIR}/public`;

  protected readonly alepha = $inject(Alepha);
  protected readonly fs = $inject(FileSystemProvider);
  protected readonly optionsStore = $store(capacitorOptions);

  /**
   * The declared options, or a refusal naming where they go.
   */
  public options(): CapacitorOptions {
    const options = this.optionsStore;
    if (!options) {
      throw new AlephaError(
        "This project declares no native app. Add capacitor({ appId, appName, scheme }) from @alepha/capacitor/cli to the plugins of alepha.config.ts.",
      );
    }
    return options;
  }

  /**
   * The native projects to manage: the declared ones, both by default.
   */
  public platforms(options: CapacitorOptions): CapacitorPlatform[] {
    return options.platforms?.length ? options.platforms : ["ios", "android"];
  }

  public configPath(root: string): string {
    return this.fs.join(root, "capacitor.config.ts");
  }

  public platformDir(root: string, platform: CapacitorPlatform): string {
    return this.fs.join(root, platform);
  }

  /**
   * The iOS app's `Info.plist`, as `cap add ios` lays it out.
   */
  public infoPlistPath(root: string): string {
    return this.fs.join(root, "ios", "App", "App", "Info.plist");
  }

  /**
   * The Android app's manifest, as `cap add android` lays it out.
   */
  public androidManifestPath(root: string): string {
    return this.fs.join(
      root,
      "android",
      "app",
      "src",
      "main",
      "AndroidManifest.xml",
    );
  }

  /**
   * The API origin the shell calls: `apiUrl` when declared, `PUBLIC_URL`
   * otherwise, `undefined` when neither is set.
   *
   * An origin and nothing more: a path, a query or a fragment is refused
   * rather than trimmed, because a caller who wrote one meant requests to go
   * there and the API's own prefix decides that.
   */
  public resolveApiUrl(options: CapacitorOptions): string | undefined {
    const publicUrl = this.alepha.env.PUBLIC_URL;
    const declared =
      options.apiUrl ?? (publicUrl ? String(publicUrl) : undefined);
    if (!declared) {
      return undefined;
    }

    let url: URL;
    try {
      url = new URL(declared);
    } catch {
      throw new AlephaError(
        `apiUrl "${declared}" is not an absolute URL. Write an origin such as https://api.example.com.`,
      );
    }

    if (url.protocol !== "https:" && url.protocol !== "http:") {
      throw new AlephaError(
        `apiUrl "${declared}" must be an http or https origin.`,
      );
    }

    if (url.pathname !== "/" || url.search || url.hash) {
      throw new AlephaError(
        `apiUrl "${declared}" must be an origin, with no path, query or fragment: ${url.origin}.`,
      );
    }

    return url.origin;
  }

  /**
   * The configuration the shell's browser code reads, built from the options
   * by allowlist: identity, mode, API origin and the declared public env.
   * Nothing else of the project's configuration or environment reaches it.
   */
  public publicConfig(
    options: CapacitorOptions,
    mode: "bundled" | "dev",
    apiUrl: string | undefined,
  ): CapacitorPublicConfig {
    return {
      appId: options.appId,
      variant: "base",
      scheme: options.scheme,
      mode,
      apiUrl,
      env: { ...options.env },
    };
  }

  /**
   * The Vite `define` that carries {@link publicConfig} into the bundle.
   */
  public defineFor(config: CapacitorPublicConfig): Record<string, string> {
    return { __ALEPHA_CAPACITOR__: JSON.stringify(config) };
  }

  /**
   * The content of `capacitor.config.ts`, from the declared options.
   *
   * Printed the way oxfmt prints it (expanded objects, trailing commas, bare
   * identifier keys), so formatting the project does not turn the next
   * command into a rewrite.
   */
  public renderCapacitorConfig(options: CapacitorOptions): string {
    const extra = { ...options.config };
    for (const key of ["appId", "appName", "webDir"]) {
      if (key in extra) {
        throw new AlephaError(
          `capacitor({ config }) cannot set ${key}: it comes from the plugin's own options.`,
        );
      }
    }
    if (
      typeof extra.server === "object" &&
      extra.server !== null &&
      "url" in extra.server
    ) {
      throw new AlephaError(
        "capacitor({ config }) cannot set server.url: it would ship a WebView pointed at a server instead of the bundled shell. `alepha capacitor dev` sets it for a development run only.",
      );
    }

    const config = {
      appId: options.appId,
      appName: options.appName,
      webDir: CapacitorProject.WEB_DIR,
      ...extra,
    };

    return [
      CapacitorProject.GENERATED_MARKER,
      "// Change capacitor({ ... }) there: the next command rewrites this file.",
      'import type { CapacitorConfig } from "@capacitor/cli";',
      "",
      `const config: CapacitorConfig = ${this.toLiteral(config, 0)};`,
      "",
      "export default config;",
      "",
    ].join("\n");
  }

  /**
   * Write `capacitor.config.ts` from the options, unless it already says the
   * same thing. A file without the generated marker is the user's and is
   * refused, never overwritten.
   */
  public async writeConfig(
    root: string,
    options: CapacitorOptions,
  ): Promise<void> {
    const path = this.configPath(root);
    const content = this.renderCapacitorConfig(options);

    if (await this.fs.exists(path)) {
      const current = await this.fs.readTextFile(path);
      if (current === content) {
        return;
      }
      this.assertOwned(current);
    }

    await this.fs.writeFile(path, content);
  }

  /**
   * Refuse a `capacitor.config.ts` the plugin did not write.
   */
  public assertOwned(content: string): void {
    if (!this.isGenerated(content)) {
      throw new AlephaError(
        "capacitor.config.ts exists and was not generated by alepha capacitor. Move its settings into capacitor({ config }) in alepha.config.ts and delete it, so the commands can own it.",
      );
    }
  }

  /**
   * Whether a file is one the plugin generated, and so may rewrite.
   */
  public isGenerated(content: string): boolean {
    return content.startsWith(CapacitorProject.GENERATED_MARKER);
  }

  /**
   * A JSON value as a TypeScript literal in oxfmt's style.
   */
  protected toLiteral(value: unknown, depth: number): string {
    const indent = "  ".repeat(depth + 1);
    const closing = "  ".repeat(depth);

    if (Array.isArray(value)) {
      const items = value.map((item) => this.toLiteral(item, depth + 1));
      const inline = `[${items.join(", ")}]`;
      if (inline.length + indent.length <= 60 && !inline.includes("\n")) {
        return inline;
      }
      return `[\n${items.map((item) => `${indent}${item},`).join("\n")}\n${closing}]`;
    }

    if (value !== null && typeof value === "object") {
      const entries = Object.entries(value).filter(([, v]) => v !== undefined);
      if (entries.length === 0) {
        return "{}";
      }
      const lines = entries.map(([key, v]) => {
        const name = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)
          ? key
          : JSON.stringify(key);
        return `${indent}${name}: ${this.toLiteral(v, depth + 1)},`;
      });
      return `{\n${lines.join("\n")}\n${closing}}`;
    }

    return JSON.stringify(value);
  }
}
