import { $inject, $store, Alepha, AlephaError } from "alepha";
import { FileSystemProvider } from "alepha/system";

import type { CapacitorPublicConfig } from "../../core/schemas/capacitorPublicConfigSchema.ts";
import {
  type CapacitorOptions,
  type CapacitorPlatform,
  capacitorOptions,
} from "../atoms/capacitorOptions.ts";

/**
 * Where everything of a native app lives, and the files the plugin owns.
 *
 * One place for the paths every `alepha capacitor` command shares: the
 * generated `capacitor.config.ts`, the shell's output directory, the two
 * native projects and the files inside them the plugin edits.
 */
export class CapacitorProject {
  /**
   * The first line of every file the plugin generates. A file that carries it
   * is the plugin's to rewrite; one that does not belongs to the user.
   */
  public static readonly GENERATED_MARKER =
    "// Generated by `alepha capacitor` from alepha.config.ts.";

  /**
   * The shell's build output, apart from the server's `dist/` so a native
   * build never moves a web deploy.
   */
  public static readonly DIST_DIR = "dist-capacitor";

  /**
   * The name of the identity declared at the top of `capacitor({ ... })`.
   */
  public static readonly BASE_VARIANT = "base";

  /**
   * The viewport of the shell's document: edge to edge, so the safe-area
   * insets are the app's to pad. Only the shell declares it; the same app
   * served as a website keeps its own.
   */
  public static readonly SHELL_VIEWPORT =
    "width=device-width, initial-scale=1, viewport-fit=cover";

  /**
   * How long the native splash may stay up on its own. The app hides it as
   * soon as its first screen settles (`react:boot:settled`), healthy or
   * failed; this backstop only covers a WebView where JavaScript never got
   * that far. The router's boot deadline (`reactBootOptions.deadline`,
   * 5000 ms by default) plus 3000 ms.
   */
  public static readonly SPLASH_BACKSTOP = 8000;

  protected readonly alepha = $inject(Alepha);
  protected readonly fs = $inject(FileSystemProvider);
  protected readonly optionsStore = $store(capacitorOptions);

  /**
   * The variant the running command works on, once {@link select}ed.
   */
  protected selected?: string;

  /**
   * Choose the identity this command works on, from its `--variant` flag,
   * and check every declared identity first.
   *
   * With variants declared, an omitted flag is refused, so a command never
   * acts on whichever variant happened to be prepared last; `base` names the
   * top-level identity. Without variants, the flag may only say `base`.
   */
  public select(variant: string | undefined): void {
    const declared = this.declared();
    this.validate(declared);
    const names = Object.keys(declared.variants ?? {});

    if (variant === undefined) {
      if (names.length > 0) {
        throw this.unselected(names);
      }
      this.selected = CapacitorProject.BASE_VARIANT;
      return;
    }
    if (variant !== CapacitorProject.BASE_VARIANT && !names.includes(variant)) {
      throw new AlephaError(
        `Unknown variant "${variant}". Declared: ${[CapacitorProject.BASE_VARIANT, ...names].join(", ")}.`,
      );
    }
    this.selected = variant;
  }

  /**
   * The options of the selected identity: the base, with the selected
   * variant's keys over it. Refused when variants exist and none was
   * selected.
   */
  public options(): CapacitorOptions {
    const declared = this.declared();
    const names = Object.keys(declared.variants ?? {});
    const selected = this.selected;

    if (selected === undefined) {
      if (names.length > 0) {
        throw this.unselected(names);
      }
      return declared;
    }
    if (selected === CapacitorProject.BASE_VARIANT) {
      return declared;
    }
    return { ...declared, ...declared.variants?.[selected] };
  }

  /**
   * The selected variant's name: `base` without variants.
   */
  public variant(): string {
    return this.selected ?? CapacitorProject.BASE_VARIANT;
  }

  /**
   * Whether `capacitor({ ... })` declares variants.
   */
  public hasVariants(): boolean {
    return Object.keys(this.optionsStore?.variants ?? {}).length > 0;
  }

  /**
   * Where the selected identity's shell is built: `dist-capacitor/` for an
   * app without variants, `dist-capacitor/<variant>/` for each identity of
   * one with variants, so no variant's build overwrites another's.
   */
  public distDir(): string {
    return this.hasVariants()
      ? `${CapacitorProject.DIST_DIR}/${this.variant()}`
      : CapacitorProject.DIST_DIR;
  }

  /**
   * The directory Capacitor copies into the native projects: the shell's
   * `public/`.
   */
  public webDir(): string {
    return `${this.distDir()}/public`;
  }

  /**
   * The options as declared, or a refusal naming where they go.
   */
  protected declared(): CapacitorOptions {
    const options = this.optionsStore;
    if (!options) {
      throw new AlephaError(
        "This project declares no native app. Add capacitor({ appId, appName, scheme }) from @alepha/capacitor/cli to the plugins of alepha.config.ts.",
      );
    }
    return options;
  }

  protected unselected(names: string[]): AlephaError {
    return new AlephaError(
      `This app declares variants (${names.join(", ")}): name the one to work on with --variant <name>, or --variant ${CapacitorProject.BASE_VARIANT} for the base identity.`,
    );
  }

  /**
   * Refuse identities that cannot be installed side by side or switched
   * between cleanly, and public env that looks like a credential.
   */
  protected validate(declared: CapacitorOptions): void {
    const variants = Object.entries(declared.variants ?? {});
    const identities: Array<[string, CapacitorOptions]> = [
      [CapacitorProject.BASE_VARIANT, declared],
      ...variants.map(([name, overrides]): [string, CapacitorOptions] => [
        name,
        { ...declared, ...overrides },
      ]),
    ];

    for (const [name] of variants) {
      if (
        name === CapacitorProject.BASE_VARIANT ||
        !/^[a-z][a-z0-9-]*$/.test(name)
      ) {
        throw new AlephaError(
          `Variant name "${name}" must be lowercase letters, digits and dashes, and cannot be "${CapacitorProject.BASE_VARIANT}".`,
        );
      }
    }

    for (const key of ["appId", "scheme"] as const) {
      const seen = new Map<string, string>();
      for (const [name, identity] of identities) {
        const other = seen.get(identity[key]);
        if (other) {
          throw new AlephaError(
            `Variants "${other}" and "${name}" share the ${key} "${identity[key]}": installed side by side, one would replace or shadow the other. Give each its own.`,
          );
        }
        seen.set(identity[key], name);
      }
    }

    if (!declared.icon && variants.some(([, overrides]) => overrides.icon)) {
      throw new AlephaError(
        "A variant declares an icon but the base does not: switching back to the base could not restore Capacitor's default icon. Declare a base icon too.",
      );
    }

    for (const [name, identity] of identities) {
      for (const key of Object.keys(identity.env ?? {})) {
        if (
          /SECRET|PASSWORD|PASSWD|TOKEN|PRIVATE|CREDENTIAL|API_?KEY/i.test(key)
        ) {
          throw new AlephaError(
            `env.${key} of "${name}" looks like a credential. env ships inside the app for anyone to read: keep secrets on the server, and signing keys in the environment of the build.`,
          );
        }
      }
    }
  }

  /**
   * The native projects to manage: the declared ones, both by default.
   */
  public platforms(options: CapacitorOptions): CapacitorPlatform[] {
    return options.platforms?.length ? options.platforms : ["ios", "android"];
  }

  public configPath(root: string): string {
    return this.fs.join(root, "capacitor.config.ts");
  }

  public platformDir(root: string, platform: CapacitorPlatform): string {
    return this.fs.join(root, platform);
  }

  /**
   * The iOS app's `Info.plist`, as `cap add ios` lays it out.
   */
  public infoPlistPath(root: string): string {
    return this.fs.join(root, "ios", "App", "App", "Info.plist");
  }

  /**
   * The Android app's manifest, as `cap add android` lays it out.
   */
  public androidManifestPath(root: string): string {
    return this.fs.join(
      root,
      "android",
      "app",
      "src",
      "main",
      "AndroidManifest.xml",
    );
  }

  /**
   * The API origin the shell calls: `apiUrl` when declared, `PUBLIC_URL`
   * otherwise, `undefined` when neither is set.
   *
   * An origin and nothing more: a path, a query or a fragment is refused
   * rather than trimmed, because a caller who wrote one meant requests to go
   * there and the API's own prefix decides that.
   */
  public resolveApiUrl(options: CapacitorOptions): string | undefined {
    const publicUrl = this.alepha.env.PUBLIC_URL;
    const declared =
      options.apiUrl ?? (publicUrl ? String(publicUrl) : undefined);
    if (!declared) {
      return undefined;
    }

    let url: URL;
    try {
      url = new URL(declared);
    } catch {
      throw new AlephaError(
        `apiUrl "${declared}" is not an absolute URL. Write an origin such as https://api.example.com.`,
      );
    }

    if (url.protocol !== "https:" && url.protocol !== "http:") {
      throw new AlephaError(
        `apiUrl "${declared}" must be an http or https origin.`,
      );
    }

    if (url.pathname !== "/" || url.search || url.hash) {
      throw new AlephaError(
        `apiUrl "${declared}" must be an origin, with no path, query or fragment: ${url.origin}.`,
      );
    }

    return url.origin;
  }

  /**
   * The configuration the shell's browser code reads, built from the options
   * by allowlist: identity, mode, API origin and the declared public env.
   * Nothing else of the project's configuration or environment reaches it.
   */
  public publicConfig(
    options: CapacitorOptions,
    mode: "bundled" | "dev",
    apiUrl: string | undefined,
  ): CapacitorPublicConfig {
    const otaUrl = options.ota
      ? this.originOf("ota.url", options.ota.url ?? apiUrl)
      : undefined;
    if (options.ota && !otaUrl && mode === "bundled") {
      throw new AlephaError(
        "capacitor({ ota }) needs the origin of the server mounting ota-api: set ota.url, or apiUrl.",
      );
    }
    return {
      appId: options.appId,
      variant: this.variant(),
      scheme: options.scheme,
      mode,
      apiUrl,
      ...(otaUrl ? { ota: { url: otaUrl } } : {}),
      env: { ...options.env },
    };
  }

  /**
   * The publisher's public key `capacitor({ ota })` declares: the PEM
   * itself, or read from the file it names.
   */
  public async otaPublicKey(
    root: string,
    options: CapacitorOptions,
  ): Promise<string | undefined> {
    const declared = options.ota?.publicKey;
    if (!declared) {
      return undefined;
    }
    const pem = declared.includes("-----BEGIN")
      ? declared
      : await this.fs.readTextFile(this.fs.join(root, declared)).catch(() => {
          throw new AlephaError(
            `capacitor({ ota }) names the public key file ${declared}, which cannot be read.`,
          );
        });
    if (!pem.includes("-----BEGIN RSA PUBLIC KEY-----")) {
      throw new AlephaError(
        "capacitor({ ota }).publicKey must be the publisher's RSA public key in PKCS#1 PEM (-----BEGIN RSA PUBLIC KEY-----). Never put the private key here.",
      );
    }
    return `${pem.trim()}\n`;
  }

  /**
   * Whether the project depends on the live updater plugin.
   */
  public async hasUpdater(root: string): Promise<boolean> {
    try {
      const pkg = JSON.parse(
        await this.fs.readTextFile(this.fs.join(root, "package.json")),
      );
      return !!(
        pkg.dependencies?.["@capgo/capacitor-updater"] ??
        pkg.devDependencies?.["@capgo/capacitor-updater"]
      );
    } catch {
      return false;
    }
  }

  protected originOf(name: string, value?: string): string | undefined {
    if (!value) {
      return undefined;
    }
    let url: URL;
    try {
      url = new URL(value);
    } catch {
      throw new AlephaError(`${name} "${value}" is not an absolute URL.`);
    }
    if (url.protocol !== "https:" && url.protocol !== "http:") {
      throw new AlephaError(
        `${name} "${value}" must be an http or https origin.`,
      );
    }
    return url.origin;
  }

  /**
   * The Vite `define` that carries {@link publicConfig} into the bundle.
   */
  public defineFor(config: CapacitorPublicConfig): Record<string, string> {
    return { __ALEPHA_CAPACITOR__: JSON.stringify(config) };
  }

  /**
   * The content of `capacitor.config.ts`, from the declared options.
   *
   * Printed the way oxfmt prints it (expanded objects, trailing commas, bare
   * identifier keys), so formatting the project does not turn the next
   * command into a rewrite.
   */
  public renderCapacitorConfig(
    options: CapacitorOptions,
    updater: { installed?: boolean; publicKey?: string } = {},
  ): string {
    const extra: Record<string, unknown> = { ...options.config };
    for (const key of ["appId", "appName", "webDir"]) {
      if (key in extra) {
        throw new AlephaError(
          `capacitor({ config }) cannot set ${key}: it comes from the plugin's own options.`,
        );
      }
    }
    if (
      typeof extra.server === "object" &&
      extra.server !== null &&
      "url" in extra.server
    ) {
      throw new AlephaError(
        "capacitor({ config }) cannot set server.url: it would ship a WebView pointed at a server instead of the bundled shell. `alepha capacitor dev` sets it for a development run only.",
      );
    }

    const plugins = { ...(extra.plugins as Record<string, unknown>) };
    plugins.SplashScreen = {
      launchAutoHide: true,
      launchShowDuration: CapacitorProject.SPLASH_BACKSTOP,
      ...(plugins.SplashScreen as Record<string, unknown>),
    };

    if (updater.installed || updater.publicKey) {
      plugins.CapacitorUpdater = this.updaterConfig(updater.publicKey, {
        ...(plugins.CapacitorUpdater as Record<string, unknown>),
      });
    }

    const config = {
      appId: options.appId,
      appName: options.appName,
      webDir: this.webDir(),
      ...extra,
      plugins,
    };

    return [
      CapacitorProject.GENERATED_MARKER,
      "// Change capacitor({ ... }) there: the next command rewrites this file.",
      'import type { CapacitorConfig } from "@capacitor/cli";',
      "",
      `const config: CapacitorConfig = ${this.toLiteral(config, 0)};`,
      "",
      "export default config;",
      "",
    ].join("\n");
  }

  /**
   * The updater's native settings: manual and silent, whatever else is
   * declared, so the plugin never calls its vendor's cloud. `autoUpdate`
   * off, every vendor URL blanked (`statsUrl: ""` turns stats off). With a
   * public key, the self-hosted policy of `@alepha/capacitor/ota`: it sets
   * the `/ota` URLs on boot (`allowModifyUrl`), from the shell's public
   * config, so the native config holds nothing machine-specific; it
   * cancels a pending bundle with `setBundleError`
   * (`allowManualBundleError`).
   */
  protected updaterConfig(
    publicKey: string | undefined,
    declared: Record<string, unknown>,
  ): Record<string, unknown> {
    return {
      ...declared,
      autoUpdate: false,
      updateUrl: "",
      statsUrl: "",
      channelUrl: "",
      ...(publicKey
        ? {
            publicKey,
            allowModifyUrl: true,
            allowManualBundleError: true,
            appReadyTimeout: 10000,
          }
        : {}),
    };
  }

  /**
   * Write `capacitor.config.ts` from the options, unless it already says the
   * same thing. A file without the generated marker is the user's and is
   * refused, never overwritten.
   */
  public async writeConfig(
    root: string,
    options: CapacitorOptions,
  ): Promise<void> {
    const path = this.configPath(root);
    const content = this.renderCapacitorConfig(options, {
      installed: await this.hasUpdater(root),
      publicKey: await this.otaPublicKey(root, options),
    });

    if (await this.fs.exists(path)) {
      const current = await this.fs.readTextFile(path);
      if (current === content) {
        return;
      }
      this.assertOwned(current);
    }

    await this.fs.writeFile(path, content);
  }

  /**
   * Refuse a `capacitor.config.ts` the plugin did not write.
   */
  public assertOwned(content: string): void {
    if (!this.isGenerated(content)) {
      throw new AlephaError(
        "capacitor.config.ts exists and was not generated by alepha capacitor. Move its settings into capacitor({ config }) in alepha.config.ts and delete it, so the commands can own it.",
      );
    }
  }

  /**
   * Whether a file is one the plugin generated, and so may rewrite.
   */
  public isGenerated(content: string): boolean {
    return content.startsWith(CapacitorProject.GENERATED_MARKER);
  }

  /**
   * A JSON value as a TypeScript literal in oxfmt's style.
   */
  protected toLiteral(value: unknown, depth: number): string {
    const indent = "  ".repeat(depth + 1);
    const closing = "  ".repeat(depth);

    if (Array.isArray(value)) {
      const items = value.map((item) => this.toLiteral(item, depth + 1));
      const inline = `[${items.join(", ")}]`;
      if (inline.length + indent.length <= 60 && !inline.includes("\n")) {
        return inline;
      }
      return `[\n${items.map((item) => `${indent}${item},`).join("\n")}\n${closing}]`;
    }

    if (value !== null && typeof value === "object") {
      const entries = Object.entries(value).filter(([, v]) => v !== undefined);
      if (entries.length === 0) {
        return "{}";
      }
      const lines = entries.map(([key, v]) => {
        const name = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)
          ? key
          : JSON.stringify(key);
        const literal = this.toLiteral(v, depth + 1);
        const line = `${indent}${name}: ${literal},`;
        // A string past the print width moves under its key, as oxfmt does.
        if (typeof v === "string" && line.length > 80) {
          return `${indent}${name}:\n${indent}  ${literal},`;
        }
        return line;
      });
      return `{\n${lines.join("\n")}\n${closing}}`;
    }

    return JSON.stringify(value);
  }
}
