name: Alepha
permissions: write-all

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    services:

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Clean
        run: yarn clean

      - name: TypeScript Check
        run: yarn check

      - name: Dependencies Check
        run: yarn check-dependencies

      - name: Test Project
        run: yarn test --coverage --reporter=junit --outputFile=test-report.junit.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy-docs:
    needs: verify
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Build Documentation
        run: yarn build:docs --base=/alepha/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/docs/dist/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-roadmap:
    needs: verify
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Build Roadmap
        run: cd apps/roadmap && yarn build

      - name: Deploy to Vercel
        run: yarn vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
